### ISSUE TITLE
Is there any example for me to check blob storage usage?

### ISSUE THREAD

**Issue by ccic** [Azure/azure-storage-java#105]
I have written a test program to evaluate the blob usage for my Azure storage, but I don't think my program's calculation is correct, because I compared the byte size of my program and the real usage on VM, they are not equal and have a big gap.

Is there any example for checking the blob storage usage?

I also found a PowerShell version of calculate blob usage/cost from online, is there a similar sample with java storage API?

My program is like:
===============================================
	public static void main(String args[]) throws InvalidKeyException, URISyntaxException, StorageException {
		CloudStorageAccount storageAccount = CloudStorageAccount.parse(storageConnectionString);
		CloudBlobClient cbc = storageAccount.createCloudBlobClient();
		Iterable<CloudBlobContainer> cIter = cbc.listContainers();
		Iterator<CloudBlobContainer> iter = cIter.iterator();
		while (iter.hasNext()) {
			CloudBlobContainer container = iter.next();
			String name = container.getName();
			long blobSize = 0;
			
			System.out.println(container.getName());
			
			Iterable<ListBlobItem> blobList = container.listBlobs();
			Iterator<ListBlobItem> blobIter = blobList.iterator();
			while (blobIter.hasNext()) {
				ListBlobItem lbi = blobIter.next();
				blobSize = 0;
				if (lbi.getClass().equals(CloudPageBlob.class)) {
					CloudPageBlob cpb = (CloudPageBlob)lbi;
					
					ArrayList<PageRange> pageRangeList = cpb.downloadPageRanges();
					for (PageRange pr : pageRangeList) {
						long pageSize = pr.getEndOffset() - pr.getStartOffset();
						blobSize += pageSize;
					}
					double blobNormalSize = blobSize;
					String result = "container '" + name + "' blob '" + cpb.getName() + "' size is " + blobNormalSize;
					
					System.out.println(result);
				} else if (lbi.getClass().equals(CloudBlockBlob.class)) {
					CloudBlockBlob cbb = (CloudBlockBlob)lbi;
					ArrayList<BlockEntry> beList = cbb.downloadBlockList();
					for (BlockEntry be : beList) {
						blobSize += be.getSize();
					}
					String result = "container '" + name + "' blob '" + cbb.getName() + "' size is " + blobSize;
					System.out.println(result);
				}
			}
		}
	}

**Comment by pemari-msft** [comment]
Try [enabling Storage Metrics and querying the capacity table.](https://msdn.microsoft.com/en-us/library/azure/hh343258.aspx)
