### ISSUE TITLE
How to iterate each different type of blob in a container

### ISSUE THREAD

**Issue by ccic** [Azure/azure-storage-java#108]
I have to iterate each blob of a specified container, but I did not find any decent way to determine the blob type except for compare the class. See the two if statements. If the ListBlobItem has blobType() method, then I don't need to compare class, but it does not support. Is there any better way to iterate different kinds of blob?

                        Iterable<ListBlobItem> blobList = container.listBlobs();
			Iterator<ListBlobItem> blobIter = blobList.iterator();
			while (blobIter.hasNext()) {
				ListBlobItem lbi = blobIter.next();
				blobSize = 0;
				if (lbi.getClass().equals(CloudPageBlob.class)) {
                                       CloudPageBlob cpb = (CloudPageBlob)lbi;
                                       ...
                                } else if (lbi.getClass().equals(CloudBlockBlob.class)) {
                                       CloudBlockBlob cbb = (CloudBlockBlob)lbi;
                                       ...
                                }
                        }

**Comment by pemari-msft** [comment]
The above will work successfully.
