### ISSUE TITLE
Error "The rate of snapshot blob calls is exceeded" for failing to create snapshot

### ISSUE THREAD

**Issue by ccic** [Azure/azure-storage-java#109]
What is the default rate of snapshot blob calls? Can I change it?

**Comment by pemari-msft** [comment]
Are you using premium storage or standard?

**Comment by ccic** [comment]
I used premium storage for test. Is there API for me to query the snapshots limit?

**Comment by pemari-msft** [comment]
No, the limit is just one snapshot per ten minutes.
