### ISSUE TITLE
Timeout connecting to Blob-only storage account through proxy

### ISSUE THREAD

**Issue by bvirkler** [Azure/azure-storage-java#111]
I am getting a connection timeout error when connecting to a Blob-only storage account (the kind with the hot/cool option) from behind a proxy.  I can connect fine using Storage Explorer or the .NET SDK.  I can connect fine from Java when not behind a proxy, or when connecting to a general storage account.  The issue only happens with the combination of java + Blob-only storage + proxy.
Using the Azure storage SDK 4.0.

**Comment by jofriedm-msft** [comment]
Hi @bvirkler ,

How are you setting up the proxy? Are you using System.setProperty() or when invoking the VM as outlined here http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html?

**Comment by bvirkler** [comment]
I was not setting the proxy explicitly.  Doing so with `System.setProperty()` did work for me.  Do you know why the proxy must be set explicitly only for this scenario?

**Comment by jofriedm-msft** [comment]
@bvirkler , I'm not sure how you were setting up the proxy previously. Just saw this was what is recommended in the Oracle documentation 😎
