### ISSUE TITLE
Facing Server Authenticating error

### ISSUE THREAD

**Issue by avneet15** [Azure/azure-storage-java#129]
I'm trying to run the sample code provided by changing to my storage account and corresponding access key.

But am facing issue:
StorageException encountered: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

I have read the resolution regarding SAS timing, but no SAS is explicitly configured by me.
Is there another known reason for the issue.
Please find atta
[AzureStorageExample.pdf](https://github.com/Azure/azure-storage-java/files/683578/AzureStorageExample.pdf)
ched below.

**Comment by jofriedm-msft** [comment]
Hi @avneet15 , I will take a closer look but noticed that the attached pdf includes your account key. Please rotate that immediately.

**Comment by avneet15** [comment]
Sure thanks. Please find attached the updated file
[AzureStorageExample.pdf](https://github.com/Azure/azure-storage-java/files/683595/AzureStorageExample.pdf)

**Comment by jofriedm-msft** [comment]
Hi @avneet15, I took a look at the sample and do not see SAS being used anywhere. Is it the first call to the service that is failing? Do you have a fiddler trace?

**Comment by avneet15** [comment]
Yes this is my first call to the service as provided in the sample code.
I haven't explicitly configured SAS. Is that something I need to do or is that done implicitly?
I assumed implicitly since it wasn't mentioned in the sample code.
No I haven't done a fiddler trace yet.

**Comment by jofriedm-msft** [comment]
This code is using shared key. More detail about it can be found here https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/authentication-for-the-azure-storage-services. SAS configuration is slightly different. Can you please share a fiddler trace?

**Comment by avneet15** [comment]
Thanks.Please find attached the file.On Jan 3, 2017, at 4:05 PM, jofriedm-msft <notifications@github.com> wrote:Hi @avneet15 , I will take a closer look but noticed that the attached pdf includes your account key. Please rotate that immediately.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azure/azure-storage-java","title":"Azure/azure-storage-java","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/Azure/azure-storage-java" class="">https://github.com/Azure/azure-storage-java</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jofriedm-msft in #129: Hi @avneet15 , I will take a closer look but noticed that the attached pdf includes your account key. Please rotate that immediately."}],"action":{"name":"View Issue","url":"<a href="https://github.com/Azure/azure-storage-java/issues/129#issuecomment-270261211" class="">https://github.com/Azure/azure-storage-java/issues/129#issuecomment-270261211</a>"}}}

**Comment by avneet15** [comment]
So the request made is : adftrialaccount.blob.core.windows.net:443/HTTP1.1.
The returned Response Header is : HTTP/1.1 200.

But the API still returns a Server Authentication failed.

**Comment by jofriedm-msft** [comment]
I don't think sharing the fiddler trace worked but it shouldn't be the status 200 request anyways. Do you see any 403 requests?

**Comment by avneet15** [comment]
Yes 403 was what I was expecting too, but only saw 200’s.
Any other means to debug?

**Comment by jofriedm-msft** [comment]
Can you try to enable client side logging? https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/Client-side-Logging-with-the-.NET-Storage-Client-Library?redirectedfrom=MSDN

If you can provide a request ID for the failing request and a timeframe, I can take a look at the server side logs.

**Comment by manjunath1992** [comment]
@avneet15 i had same issue and it because of time. sync time and date after try. this may help.

**Comment by avneet15** [comment]
Can you elaborate on this?
Do I need to sync with a specific timezone?

**Comment by avneet15** [comment]
@jofriedm-msft  The details are: {Response received. Status code = '200', Request ID = '6b428566-0001-0003-68b9-6657d3000000', Content-MD5 = 'null', ETag = '"0x8D4342C131E15CD"', Date = 'Wed, 04 Jan 2017 18:35:43 GMT'.}

**Comment by avneet15** [comment]
Don't see that in my logs. Here they are:

0    [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Starting operation.}
2    [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Starting operation with location 'PRIMARY' per location mode 'PRIMARY_ONLY'.}
174  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Starting request to 'https://adftrialaccount.blob.core.windows.net/sample?restype=container' at 'Wed, 04 Jan 2017 18:35:44 GMT'.}
174  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Waiting for response.}
303  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Response received. Status code = '200', Request ID = '6b428566-0001-0003-68b9-6657d3000000', Content-MD5 = 'null', ETag = '"0x8D4342C131E15CD"', Date = 'Wed, 04 Jan 2017 18:35:43 GMT'.}
304  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Processing response headers.}
304  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Response headers were processed successfully.}
304  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Processing response body.}
304  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Response body was parsed successfully.}
306  [main] INFO  root  - {ce4841a4-42c3-474b-9089-b07c0cfe1216}: {Operation completed.}

**Comment by jofriedm-msft** [comment]
Yes, everything looks like it is working in those logs. Where are you seeing the 403? Are you running any other samples that may be using another service besides blob and that is why you can't see them in Fiddler?

**Comment by avneet15** [comment]
@jofriedm-msft Yes it just started working now. Not sure what changed.

**Comment by jofriedm-msft** [comment]
😎
