### ISSUE TITLE
Feature Request: Ability to configure a HttpRequestInterceptor on the OperationContext

### ISSUE THREAD

**Issue by nithinmahesh** [Azure/azure-storage-java#130]
Hi,

We are using the proxying feature in Azure Storage SDK to route requests through a Proxy. For supporting a new scenario, we need to pass additional information to the proxy which will not fit in the headers. 
Hence we would like to get support for adding a http request interceptor to the operation context so that we can add this information to the request body and extract it out on the proxy.

Thanks,
Nithin

**Comment by jofriedm-msft** [comment]
Hi @nithinmahesh , how much data are you trying to add to the headers? Would it be possible to split this data across multiple headers?

**Comment by nithinmahesh** [comment]
Thanks @jofriedm-msft . We are looking at adding around 8K. It is safe to have the request line plus header fields not exceed 8KB so that it can be accepted by any server. So it is not about the limit of one header field but actually the limit of all header fields together that blocks us.

**Comment by jofriedm-msft** [comment]
@nithinmahesh , have you attempted to send more than 8KB to the proxy. For instance IIS can support more than 8KB. Otherwise you can try setting up a local proxy on the machine generating the requests and have this modify the body.
