### ISSUE TITLE
Test failures while creating jar package

### ISSUE THREAD

**Issue by ramandeep1991** [Azure/azure-storage-java#131]
My project is non maven,so needed jar to use storage api.Trying to create a sdk jar file using maven,but there is build faliure due to 1029 errors during plugin goal test.Most are Null pointer exceptions in SasTests class.

**Comment by jofriedm-msft** [comment]
Hi @ramandeep1991 , can you go over the steps you took in more detail? Is there a stack trace with the null pointer exception? You will need to input your storage credentials in order to run the tests.
