### ISSUE TITLE
command to compile this sdk in README is outdated.

### ISSUE THREAD

**Issue by xinglin** [Azure/azure-storage-java#137]
The "mvn compile" command should be run in the azure-storage-java dir, rather than the dir "./azure-storage-java/microsoft-azure-storage"

-------------------------------
Option 2: Source Via Git

To get the source code of the SDK via git just type:

git clone git://github.com/Azure/azure-storage-java.git
cd ./azure-storage-java/microsoft-azure-storage
mvn compile
--------------------------------

**Comment by jofriedm-msft** [comment]
Yes, you are correct. Thanks for pointing this out! I will update this now 😎
