### ISSUE TITLE
exists() does not respect RequestLocationMode

### ISSUE THREAD

**Issue by dadoonet** [Azure/azure-storage-java#140]
Hi there

While I was working on [an issue with elasticsearch Azure repository](https://github.com/elastic/elasticsearch/issues/23480), I went to [this part of the code](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudBlob.java#L1858-L1861):

```java
    private StorageRequest<CloudBlobClient, CloudBlob, Boolean> existsImpl(final boolean primaryOnly,
            final AccessCondition accessCondition, final BlobRequestOptions options) {
        final StorageRequest<CloudBlobClient, CloudBlob, Boolean> getRequest = new StorageRequest<CloudBlobClient, CloudBlob, Boolean>(options, this.getStorageUri()) {
            @Override
            public void setRequestLocationMode() {
                this.setRequestLocationMode(primaryOnly ? RequestLocationMode.PRIMARY_ONLY
                        : RequestLocationMode.PRIMARY_OR_SECONDARY);
            }

//...
```

[In my code](https://github.com/elastic/elasticsearch/blob/5.x/plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java#L219-L230), I'm calling this:

```java
    @Override
    public boolean blobExists(String account, LocationMode mode, String container, String blob) throws URISyntaxException, StorageException {
        // Container name must be lower case.
        CloudBlobClient client = this.getSelectedClient(account, mode);
        CloudBlobContainer blobContainer = client.getContainerReference(container);
        if (blobContainer.exists()) {
            CloudBlockBlob azureBlob = blobContainer.getBlockBlobReference(blob);
            return azureBlob.exists();
        }

        return false;
    }
```

Here is a subpart of the [getSelectedClient()](https://github.com/elastic/elasticsearch/blob/5.x/plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java#L102-L147) method:

```java
client.getDefaultRequestOptions().setLocationMode(mode);
```

Sometimes my user wants to use a `SECONDARY_ONLY` location mode.
It works well with all the APIs I'm using but I think that I don't have any way to use only the secondary location when calling exists.

I wonder if it's a bug or if this has been done on purpose. 

Let me be clear: I'm fine with this behavior for my use case although it does not respect the "contract" of secondary only repo.
So if you think it's a bug and are willing to change it, I will probably need to change a bit my code as in the case of secondary only, I don't want to have any retry policy but fail immediately if the blob is not available.

Thanks for reading!

**Comment by jofriedm-msft** [comment]
Hi @dadoonet, I am not sure if follow. I checked the code and ran a test to verify. If the BlobRequestionOptions are set to SECONDARY_ONLY the request to exists() are going to the secondary endpoint without going to the primary. Here is the sample test for reference if you want to see how to do this.

CloudBlobContainer container = bClient.getContainerReference("testContainer");
        container.createIfNotExists();
        CloudPageBlob blob2 = container.getPageBlobReference("blob2");
        blob2.deleteIfExists();
        blob2.create(1024);
        BlobRequestOptions options = new BlobRequestOptions();
        options.setLocationMode(LocationMode.SECONDARY_ONLY);
        blob2.exists(null, options, null); // can also set on the client and not pass the options for every request by doing bClient.setDefaultRequestOptions(options);

**Comment by dadoonet** [comment]
Thanks for the feedback. I probably misread your code.
Thanks for confirming.

I'm closing and I'll reopen if needed. Best!

**Comment by dadoonet** [comment]
Reading again your code I don't understand how it goes to the secondary repo only when you call `exists()`.

```java
    public final boolean exists() throws StorageException {
        return this.exists(null /* accessCondition */, null /* options */, null /* opContext */);
    }
```

This is calling:

```java
    public final boolean exists(final AccessCondition accessCondition, BlobRequestOptions options,
            OperationContext opContext) throws StorageException {
        return this.exists(false /* primaryOnly */, accessCondition, options, opContext);
    }
```

Note the `false` here.

This is calling:

```java
    private final boolean exists(final boolean primaryOnly, final AccessCondition accessCondition,
            BlobRequestOptions options, OperationContext opContext) throws StorageException {
        if (opContext == null) {
            opContext = new OperationContext();
        }

        opContext.initialize();
        options = BlobRequestOptions.populateAndApplyDefaults(options, this.properties.getBlobType(), this.blobServiceClient);

        return ExecutionEngine.executeWithRetry(this.blobServiceClient, this,
                this.existsImpl(primaryOnly, accessCondition, options), options.getRetryPolicyFactory(), opContext);
    }
```

Where `primaryOnly` is equal to `false` as we just saw.

Then you have:

```java
    private StorageRequest<CloudBlobClient, CloudBlob, Boolean> existsImpl(final boolean primaryOnly,
            final AccessCondition accessCondition, final BlobRequestOptions options) {
        final StorageRequest<CloudBlobClient, CloudBlob, Boolean> getRequest = new StorageRequest<CloudBlobClient, CloudBlob, Boolean>(
                options, this.getStorageUri()) {
            @Override
            public void setRequestLocationMode() {
                this.setRequestLocationMode(primaryOnly ? RequestLocationMode.PRIMARY_ONLY
                        : RequestLocationMode.PRIMARY_OR_SECONDARY);
            }
// ...
```

Again here `primaryOnly` is `false` right?

So when the request is built, I assume we do this:

```java
                this.setRequestLocationMode(primaryOnly ? RequestLocationMode.PRIMARY_ONLY
                        : RequestLocationMode.PRIMARY_OR_SECONDARY);
```

Which becomes:

```java
                this.setRequestLocationMode(false ? RequestLocationMode.PRIMARY_ONLY
                        : RequestLocationMode.PRIMARY_OR_SECONDARY);
```

Which means:

```java
                this.setRequestLocationMode(RequestLocationMode.PRIMARY_OR_SECONDARY);
```


Am I missing something?

**Comment by pemari-msft** [comment]
Yes. You're misunderstanding the difference between `RequestLocationMode` and `LocationMode`. `RequestLocationMode` represents the *possible* locations to send a certain type of request to. The ExecutionEngine will do the reconciliation between the possible locations and the location you chose, and it'll go to secondary.

**Comment by dadoonet** [comment]
I see. Thanks for the clarification!
