### ISSUE TITLE
BlobInputStream: Allow pre-fetch of multiple pages ahead of the read position

### ISSUE THREAD

**Issue by shanielh** [Azure/azure-storage-java#142]
Allow pre-fetch of multiple pages ahead of the current read position so that the user will read "smaller" chunks of data in streaming matter for systems with less memory usage.

It's pretty much done in the [OutputStream](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/BlobOutputStreamInternal.java#L171).

What do you think?

**Comment by jofriedm-msft** [comment]
Hi @shanielh, we are planning on adding enhancements to our download logic in an upcoming release. I don't have a timeline but can update this thread when the timeline is more clear.

Thanks!
