### ISSUE TITLE
Need Ability to copy across StorageAccounts

### ISSUE THREAD

**Issue by brokenjpl** [Azure/azure-storage-java#149]
Hi there,

According to these docs (https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) we should be able to copy Blobs across storage account. In doesn't look like this functionality is available in this SDK.  If it is already possible, could you please provide an example?

Thanks!

**Comment by pemari-msft** [comment]
You can use the [startCopy](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudBlob.java#L651) method to initiate a copy to another Account. The URI will need a valid SAS token to work successfully.
