### ISSUE TITLE
startCopy succeeded but size of the file is 0

### ISSUE THREAD

**Issue by kennethinsnow** [Azure/azure-storage-java#160]
We run a backup job to copy files from one storage account to another.
We use startcopy as below:
```
            CloudBlockBlob target = backUpContainer.getBlockBlobReference(path);
            CloudBlockBlob src = getSASBlobReference((CloudBlockBlob) file);
            if (!target.exists()) {
                    target.startCopy(src);
            }
```
We have been running this code for a year, and it was ok at the beginning, but recently we found most of the files copied have size as 0. We can see the filename, directory, but majority of the files are 0 in size. though some files are ok.
We are still using azure-storage version 4.0.0. Is there some change in the backend that can cause this problem?

**Comment by mirobers** [comment]
If you are copying between storage accounts, it is likely that the copies are asynchronous. You can check the status of the copy using `getCopyState().getStatus()` on the blob properties. If this is `PENDING` then the copy is still in progress. You can poll for completion using `downloadAttributes` and checking the copy status.

**Comment by kennethinsnow** [comment]
Thanks. I understand its asynchronous. But most of these data are copied days ago. We keeps copy for 30 days, and most of those files have 0 size.

**Comment by mirobers** [comment]
Did you poll the copy status of the blobs to ensure that they were successfully copied?

**Comment by kennethinsnow** [comment]
Unfortunately no. Our application doesn't allow block calls. 
Does it matter if we delete the source once the copy command is accepted by Azure. Does azure guarantee the copy happens before the deletion?

**Comment by pemari-msft** [comment]
It does not. You likely deleted the blobs before they were successfully copied, thus causing the copy to fail, leaving the empty blobs.
