### ISSUE TITLE
What's the best way to backup azure storage account

### ISSUE THREAD

**Issue by kennethinsnow** [Azure/azure-storage-java#161]
We currently have 70-100 TB data in azure blob storage. We want to defend against the errors on our side (accidentally delete data for example) by keeping multiple copies/snapshots of our data. What's the best way to do it?
1. Can we take a snapshot for our Container every 15 days, and then take incremental snapshot every day? We will also need to move this snapshot to another storage account to avoid any single account issue. Is it possible? How long would it take to copy it over?
2. Does azure have ways to setup a backup plan to periodically back our data?

Thanks

**Comment by kennethinsnow** [comment]
I came across this strategy to copy each blob. Is it still valid as the post is 5 years old, and do you have an idea how long that's gonna take for account of our scale?
http://stackoverflow.com/questions/11561844/what-is-the-best-way-to-backup-azure-blob-storage-contents

**Comment by mirobers** [comment]
Yes, the blog post linked in that answer is valid. You might be interested in the [AzCopy](https://docs.microsoft.com/en-us/azure/storage/storage-use-azcopy#blob-copy) tool to help with this. Possibly [Azure Backup](https://docs.microsoft.com/en-us/azure/backup/backup-introduction-to-azure-backup) would be worth looking at too.

**Comment by kennethinsnow** [comment]
Thanks a lot, Mike. Azcopy is very convenient, but kinda slow for our scale. I can get it transferring at 3m/s with a two core VM, but for 70Tb that would take months (for the first backup). I feel its not really an asyn process, its still blocked on each blob copy to finish.
Azure backup seems to be only for vm, well-defined data type, i don't see how it can backup azure storage data at the container level.
Do you know which department in azure we should talk to about this solution? I know this may not related to java client, but i really appreciate you guys being super responsive.

**Comment by mirobers** [comment]
@kennethinsnow Server-side copy happens in the background and it is typically slower than what you can achieve by using an Azure VM to download and upload the data yourself. I encourage you to experiment to see if async server-side or sync download/upload work best for your scenario.

**Comment by seguler** [comment]
For those who are looking at this issue in 2019: AzCopy today can copy an account as fast as 50Gbps thanks to the new copy APIs we have released recently. All AzCopy does is to orchestrate the copy - Storage service copies data directly from a given source URL, hence eliminating a bottleneck.
