### ISSUE TITLE
Tracing API calls with Log4j

### ISSUE THREAD

**Issue by renutz** [Azure/azure-storage-java#167]
Hi,

I searched on the docs and I could not find a way to log the API calls that azure-storage is doing.

In Azure java sdk (https://github.com/Azure/azure-sdk-for-java), it is simple and works. Just a configuration on log4j:

log4j.logger.com.microsoft.azure.management=DEBUG

We tried something similar but it did not work

log4j.logger.com.microsoft.azure.storage=DEBUG

What are we missing?

Thanks

**Comment by pemari-msft** [comment]
We use slf4j. Please take a look at our documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/client-side-logging-with-the-microsoft-azure-storage-sdk-for-java). Thanks!
