### ISSUE TITLE
blob.getUri() returns uri not fully encoded

### ISSUE THREAD

**Issue by litel-fr** [Azure/azure-storage-java#168]
When uploading a file named "aaa/something™ foo, bar.txt", the blob uri returned is
".../aaa/something™%20foo,%20bar.txt". Both "™" and "," are not encoded 

code :
```java
CloudBlockBlob blob = container.getBlockBlobReference(uploadName);     
File source = new File(fileUri);
FileInputStream sourceStream = new FileInputStream(source);
blob.upload(sourceStream, source.length());
URL url = blob.getUri().toURL();
```

Is this the expected behavior ?

**Comment by jofriedm-msft** [comment]
Hi @litel-fr , this is encoded across the wire (something%E2%84%A2%20foo,%20bar.txt) but when calling getURL() you are seeing the unecoded version which also matches what is returned from a list blobs call by the service i.e. <Blob><Name>something™ foo, bar.txt</Name>
