### ISSUE TITLE
azure table storage client support cosmos table DB

### ISSUE THREAD

**Issue by manjunath1992** [Azure/azure-storage-java#186]
Is azure storage java client supports cosmos DB (backed with azure table) ?

else any future support or separate client for cosmos table DB ?

**Comment by zezha-msft** [comment]
Hi @manjunath1992. CosmosDB is not part of Azure Storage, so our Java library will not support CosmosDB.

Here is the official alias for all CosmosDB related questions: askcosmosdb at microsoft dot com

Thanks 😄
