### ISSUE TITLE
Occasional javax.net.ssl.SSLException on CloudBlockBlob.upload()

### ISSUE THREAD

**Issue by Draczech** [Azure/azure-storage-java#187]
Hi, recently I've been testing blob storage upload from multiple devices using:
- Java(TM) SE Embedded Runtime Environment (build 1.8.0_111-b14, headless)
- azure-storage 5.0.0

And on one device I'm getting following exception when trying to upload a file into a blob:
_javax.net.ssl.SSLException: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available_

It has the same HW, FW, truststores and credentials as other devices I've been working with, but other devices keep working fine while this particular device cannot upload single file. I've tried to change to different subscription with different blob storage, but I've been just partially successful. I've managed to upload some files (around 50KB), but then I was experiencing the same problem again.

Thanks for any ideas which can direct me to the cause of this issue (or to solution even bettter... )

**Comment by jofriedm-msft** [comment]
Hi @Draczech , from my brief search online it looks like this is a bug in Java 8 that was reported fixed but apparently customers are still hitting it. https://bugs.centos.org/view.php?id=9482
You can try using a different version of java and see if that resolves the issue.
Also we have a 5.3.1 version of the library out 😎

**Comment by Draczech** [comment]
Hi and sorry I couldn't get to your message earlier (due to my vacation and some public holiday...)
1. Yes, I agree that we don't use the latest Java version available, but it is not that old either. Since updating Java on our devices is not exactly simplest solution to this problem and apparently it is not guaranteed to fix the issue AFAIK, I'd preffer some other way of preventing this issue from hapenning. It is also strange that it occurs on one device while the others are working fine.
2. I tried the 5.3.1 release of the library, but in the OSGI environment we use I cannot even start my bundle due to:

` java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.storage.core.Utility
        at com.microsoft.azure.storage.CloudStorageAccount.parse(CloudStorageAccount.java:242)`
