### ISSUE TITLE
Create container throwing SSLHandshakeException for china cloud(MC) for https blob endpoint

### ISSUE THREAD

**Issue by snallami** [Azure/azure-storage-java#19]
Code below works fine for US cloud but for china cloud it is failing with error 

'''
	public static void createContainer(String storageAccountName, String key, String containerName, String storageURI) throws Exception {
        try {
            CloudStorageAccount cloudStorageAccount = getCloudStorageAccount(storageAccountName, key, storageURI);
            CloudBlobClient blobClient = cloudStorageAccount.createCloudBlobClient();
            CloudBlobContainer container = blobClient.getContainerReference(containerName);
            // Create the container if it does not exist
            container.createIfNotExists();
        } catch (Exception ex) {
        	throw ex;
        }
	}
'''

Expection message:
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

since there is no special handling required for US cloud for https urls expectation is china cloud (MC) also should work in similar manner.

For US cloud , SSL Root authority is “Baltimore CyberTrust Root” and verified by “MSIT Machine Auth CA 2”
For China cloud, SSL Root authority is “CNNIC SSL” and verified also by “CNNIC SSL”

Looks like china cloud SSL root authority is not under trusted cert list in JDK , hence calls to storage like createContainer are failing if we use china cloud https endpoint.

I am using 0.7.0 version of storage but same issue should be there for latest version as well

**Comment by emgerner-msft** [comment]
Closing as we communicated with this user offline.

**Comment by zp-j** [comment]
Hi @emgerner-msft, we encountered the same issue, would you like to give some hints here? Thanks!
