### ISSUE TITLE
Is there a way to index custom columns in Azure Table Storage

### ISSUE THREAD

**Issue by AzureUser123** [Azure/azure-storage-java#196]
Currently azure has 3 indexed searches-partitionKey, rowKey and timestamp. In addition to these, can we index another column? We can do a table scan with non-indexed column, but it'll take some time if the table is large.

**Comment by jofriedm-msft** [comment]
Hi @AzureUser123 , the table service cannot index additional columns for you. However, there are a few options to get around this. Please take a look at them [here] (https://docs.microsoft.com/en-us/azure/storage/storage-table-design-guide#index-entities-pattern)
