### ISSUE TITLE
Azure search service

### ISSUE THREAD

**Issue by AzureUser123** [Azure/azure-storage-java#197]
Can we use Azure search service in our code base to query the table? If so how can we do that?

**Comment by jofriedm-msft** [comment]
According to their documentation, it looks like Azure Tables are [supported](https://docs.microsoft.com/en-us/rest/api/searchservice/index). They have getting started info [here](https://docs.microsoft.com/en-us/azure/search/search-get-started-java) as well as a [github with samples](https://github.com/Azure-Samples/search-java-getting-started) that you can contact them at for more info.
