### ISSUE TITLE
Asynchronous call for Downloading Blob

### ISSUE THREAD

**Issue by Sathyahw** [Azure/azure-storage-java#216]
While going through the API calls available, I came to notice the following in c++ SDK,

`void  download_to_stream (concurrency::streams::ostream target)
  Downloads the contents of a blob to a stream. More...`
`pplx::task< void >  download_to_stream_async (concurrency::streams::ostream target)
  Intitiates an asynchronous operation to download the contents of a blob to a stream.`

But in case of **JAVA, there is no Async calls available in SDK**. It is a blocking call right now. It would be very handy if the SDK itself provides an asynchronous call.

**Comment by jofriedm-msft** [comment]
Hi @Sathyahw, we are actively working on this! And have issue #122 tracking this
