### ISSUE TITLE
Weblogic connectivity issues

### ISSUE THREAD

**Issue by UmeetVaswani** [Azure/azure-storage-java#217]
I am facing issues while creating a container on Azure Storage with Weblogic.
With tomcat there are no such issues.
It says : 
Http-Method: GET
Content-Type:
Headers: {Accept=[*/*], accept-encoding=[gzip, deflate], Accept-Language=[en-US,en;q=0.5], connection=[keep-alive], Content-Type=[null], DNT=[1], Host=[localhost:7001], Referer=[http://localhost:7001/AzureStorage/], User-Agent=[Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0], X-Requested-With=[XMLHttpRequest]}
--------------------------------------
##################################################################################
com.microsoft.azure.storage.StorageException: The server encountered an unknown failure: Length Required
Sep 18, 2017 12:40:21 PM org.apache.cxf.interceptor.LoggingOutInterceptor
INFO: Outbound Message
---------------------------
ID: 2
Response-Code: 204
Content-Type: text/html
Headers: {Date=[Mon, 18 Sep 2017 10:40:21 GMT], Content-Length=[0]}

Please help it is quite urgent for me

**Comment by jofriedm-msft** [comment]
Hi @UmeetVaswani, sorry for the late response. The Length Required means that most likely, the Content-Lenght header is not being sent.  I see in the first part of the message it looks like you are sending it through a proxy? Can you please take a look at this stackoverflow posts https://stackoverflow.com/questions/43067899/creating-azure-storage-container-fails-when-deploying-on-weblogic-12c and https://stackoverflow.com/questions/35185987/specifying-proxyuser-and-proxypassword-thru-proxy-server-microsoft-azure-storage
