### ISSUE TITLE
API changes review for Azure Storage Client SDK

### ISSUE THREAD

**Issue by lvc** [Azure/azure-storage-java#218]
The review of API changes for the Azure Storage Client SDK library since 1.1.0 version: https://abi-laboratory.pro/java/tracker/timeline/azure-storage/

The report is updated 3 times a week (Mon, Wed, Fri). Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools.

Thank you.

![azure storage client sdk-2](https://user-images.githubusercontent.com/1517837/30953149-b05ddb2a-a43b-11e7-852f-0c795d867526.png)
![azure storage client sdk-1](https://user-images.githubusercontent.com/1517837/30953148-b05bc8a8-a43b-11e7-9ea1-20d7eedd7c61.png)

**Comment by mirobers** [comment]
Thanks for sharing this. It is interesting, but not actionable. The reported compatibility issues appear to be for internal-only members.

**Comment by lvc** [comment]
@mirobers,

Where can I find list of public classes/packages?

Thank you.

**Comment by mirobers** [comment]
We have this in the source code. Classes with the public qualifier contain a comment saying that it's for internal use only. We do this because we need inter-package communication even for internal classes.
