### ISSUE TITLE
Setting UserAgent string

### ISSUE THREAD

**Issue by mmarsala** [Azure/azure-storage-java#219]
Is there a recommended way to override the UserAgent string sent in to the HTTP Connection in the BaseRequest class? It looks like we can override UserAgent using the regular Azure SDK for Java (https://azure.github.io/azure-sdk-for-java/index.html?com/microsoft/azure/AzureServiceClient.html) but we have not found a way to do this with the storage-specific SDK.

We are working on an application to replicate from files on-prem to Azure blobs and the Azure Storage PM team has requested that we tag the calls that we make.

Thanks for your help,
Matt

**Comment by jofriedm-msft** [comment]
Hi @mmarsala , we are planning on exposing the ability to prepend to UserAgent string. I will check to see if this will be in the next release or not and update this thread.
