### ISSUE TITLE
Release 6.1.0 was tagged as `v6.0.1`

### ISSUE THREAD

**Issue by Stephan202** [Azure/azure-storage-java#229]
Compare:
* https://github.com/Azure/azure-storage-java/compare/v6.0.0...v6.1.0: Doesn't work; tag doesn't exist.
* https://github.com/Azure/azure-storage-java/compare/v6.0.0...v6.0.1: Works, but shouldn't (presumably).

**Comment by jofriedm-msft** [comment]
Thanks for pointing this out! It should be fixed now
