### ISSUE TITLE
Error when trying with Azure gov endpoints. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-storage-java#232]
I am trying to use gov endpoints with the Azure Gov endpoints.  My code is as follows. 

CloudStorageAccount account = CloudStorageAccount.parse(connectionString); 

connectionString has the suffix of Gov cloud. For some reason the values for the blob.storage URI are still marked as blob.core.windows.net and I receive the following error. I am unable to run any blob operations. 

```
com.microsoft.azure.storage.StorageException: The server encountered an unknown failure:
 at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:178)
 at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:214)
 at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:749)
 at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:736)
 at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:710)
 at com.scalegrid.cloudconnector.azure.AzureStorageClient.createContainerIfItDoesntExist(AzureStorageClient.java:369)

 java.net.UnknownHostException: XXXX.core.usgovcloudapi.net
ERROR ~ s failed.
 Code:12207
```
Is there any way I can get this to work ?

**Comment by jofriedm-msft** [comment]
Hi @nwarriorch , what are you passing for your connection string? Please obfuscate the key.

You need to make sure you are passing the endpoint suffix. Here is an example

CloudStorageAccount.parse("DefaultEndpointsProtocol=https;AccountName=[ACCOUNT_NAME];AccountKey=[ACCOUNT_KEY];EndpointSuffix=core.usgovcloudapi.net");

**Comment by nwarriorch** [comment]
"DefaultEndpointsProtocol=https;AccountName=%s;AccountKey=%s;EndpointSuffix=core.usgovcloudapi.net";

This is what I am using.

**Comment by jofriedm-msft** [comment]
Hmm ok, I had tested this with our latest code and it appears to work. There may have been a bug in an older version. Are you able to try upgrading and see if that works for you?

**Comment by nwarriorch** [comment]
when I use just 

`CloudStorageAccount account = CloudStorageAccount.parse(connectionString);`
`account.getBlobEndpoint() ` gives the value ` "https://xxxx.core.windows.net"` instead of `"https://xxxx.core.usgovcloudapi.net"`

I also tried using a different constructor like 


```
CloudStorageAccount account = CloudStorageAccount.parse(connectionString);
CloudStorageAccount accountConstruct = new CloudStorageAccount(account.getCredentials(), new Uri("https://xxxx.core.usgovcloudapi.net"), account.getFileEndpoint(), account.getQueueEndpoint(), account.getTableEndpoint());
account = accountConstruct;
```

This throws the exception 

`ava.net.UnknownHostException: XXXX.core.usgovcloudapi.net`

**Comment by nwarriorch** [comment]
I will try a newer version and check if the bug is fixed.

**Comment by nwarriorch** [comment]
I tested with 6.2.0. This bug is resolved.  Thank you.
