### ISSUE TITLE
Multiple deletes using a single API for blobs having common prefix

### ISSUE THREAD

**Issue by pratt06** [Azure/azure-storage-java#236]
Is there a plan to create an API for deleting multiple blobs which have a common prefix e.g.
ab/cd/ef/test1.png
ab/cd/hg/test2.png
So, if we call the API with prefix ab/cd it can delete both.

Also, is there a plan to have an API which when provided a list of blob keys, deletes all of them?

We want to avoid the maintenance overhead of creating our own workers to perform the same thing.

**Comment by jofriedm-msft** [comment]
Hi @pratt06 , we currently don't support this but can add this as a feature request for the service

**Comment by jofriedm-msft** [comment]
This is very doable to implement client-side though. You can call list blobs providing the prefix you would like and as you enumerate the results you can delete the blobs.

**Comment by mirobers** [comment]
For service support, feel free to add this suggestion to [UserVoice](https://feedback.azure.com/forums/217298-storage/search?filter=new&oauth_consumer_key=GXzk8Xs15zfBxRjoH2Jgzg&oauth_signature_method=HMAC-SHA1).

On the client, we don't have plans to support these operations. As jofriedm mentioned, you can implement this and tailor it to your specific needs.
