### ISSUE TITLE
Can't copy from BlockBlob to File

### ISSUE THREAD

**Issue by srlps** [Azure/azure-storage-java#238]
I am trying to copy a blob into a file with this code:

    try {

        String storageConnectionString = String.format(storageConnectionStringTemplate, accountName, accountKey);

        StorageCredentials credentials = StorageCredentials.tryParseCredentials(storageConnectionString);

        CloudFile file = new CloudFile(new URI("FileUri"), credentials);

        CloudBlockBlob blob = new CloudBlockBlob(new URI("BlobUri"), credentials);

        if(!blob.exists()){
            throw new Exception("No blob");
        }

        if (!file.exists()) {
            file.create(blob.getProperties().getLength());
            Thread.sleep(3000);
        }

        file.startCopy(blob);
    } catch (StorageException e) {
        System.out.println("Message: " + e.getMessage());
        System.out.println("Error Code: " + e.getErrorCode());
        System.out.println("Additional Details: " + e.getExtendedErrorInformation().getAdditionalDetails().toString());
        System.out.println("HTTP Status Code: " + e.getHttpStatusCode());
        System.out.println(e.getMessage());
    } catch (Exception e) {
        System.out.println(e.getMessage());
        e.printStackTrace();
    }
But I'm getting this exception when trying to execute the "file.startCopy(blob);" line.

    Message: The specified resource does not exist.
    Error Code: CannotVerifyCopySource
    Additional Details: {}
    Status Code: 404
Apparently, the source blob of the copy is not found. But, this block of code shows the opposite:

    if(!blob.exists()){
        throw new Exception("No blob");
    }
I have verified that the copy source exists, so I don'd know what to do anymore. Please help.

**Comment by jofriedm-msft** [comment]
Hi @srlps , if you take a look at the [MDSN spec](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-file) it mentions that when copying from a blob, you will need to provide a SAS token or set the blob to [public access](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-access-to-resources) or append a SAS token. There is an example test showing how to do this, called [testCopyBlockBlobSas](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/file/CloudFileTests.java)

**Comment by srlps** [comment]
Thanks!
I have made the changes you suggested and it worked.
I'll leave my code for references.

    String storageConnectionString = String.format(storageConnectionStringTemplate, accountName, accountKey);

    StorageCredentials credentials = StorageCredentials.tryParseCredentials(storageConnectionString);

    CloudFile file = new CloudFile(new URI("FileUri"), credentials);

    CloudBlockBlob blob = new CloudBlockBlob(new URI("BlobUri"), credentials);

    if(!blob.exists()){
        throw new Exception("No blob");
    }

    if (!file.exists()) {
        file.create(blob.getProperties().getLength());
    }

    SharedAccessBlobPolicy containerPolicy = blob.getContainer().downloadPermissions().getSharedAccessPolicies().get("my-policy");

    String sasToken = blob.generateSharedAccessSignature(containerPolicy, null, null);

    StorageCredentialsSharedAccessSignature sasCredentials = new StorageCredentialsSharedAccessSignature(sasToken);
    Constructor<? extends CloudBlob> blobType = blob.getClass().getConstructor(URI.class);
    file.startCopy(blobType.newInstance(sasCredentials.transformUri(blob.getUri())));
