### ISSUE TITLE
is there 'connection pool' like option(s) in Java SDK?

### ISSUE THREAD

**Issue by electronicnomad** [Azure/azure-storage-java#239]
I am looking for options like below .NET SDK codes in Java,

```
blobEndpoint.UseNagleAlgorithm<-false
blobEndpoint.ConnectionLimit<-1000
blobEndpoint.MaxIdleTime<-Timeout.Infinite
```
and [BufferManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobclient.buffermanager?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Blob_CloudBlobClient_BufferManager)

**Comment by jofriedm-msft** [comment]
Hi @electronicnomad , the only one of those currently configurable is the connection limit which can be set globally using System.SetProperty(“http.maxConnections” [number]);

There is no BufferManager in Java
