### ISSUE TITLE
how to download all files in the folder

### ISSUE THREAD

**Issue by mayong1030** [Azure/azure-storage-java#241]
i use app service of Azure,  Automatically save the file to  the storage.The directory is created according to the time. i want to download files of one day. how to download by azure stroage java SDK. 
ex:
Location:palladiumuprodlog/PALLADIUMU/2017/12/01/00

**Comment by jofriedm-msft** [comment]
Hi @mayong1030, if you have the files stored in a specific directory you can simply list all of the files and then download each one. I don't know your use case/if you are actually using Azure Files vs Block blobs which is much more common but here's a link to a bunch of samples which include listing and downloading for both https://docs.microsoft.com/en-us/azure/storage/common/storage-samples-java

**Comment by mirobers** [comment]
Closing this issue, but feel free to reopen if you have more questions.
