### ISSUE TITLE
CloudBlockBlob upload and metadata

### ISSUE THREAD

**Issue by mkozioro** [Azure/azure-storage-java#243]
Hi,

I have a question for upload method in CloudBlockBlob. Is upload method always uploading changed metadata of the object or I always need to always run uploadMetadata method?

It's not that obvious when reading upload(InputStream, length, AccessCondition, BlobRequestOptions, OperationContext) source code, because uploadFullBlob method looks like uploading metadata, and for the rest I'm not that sure. 

I'm asking because I want to limit calls to blob storage api and therefore minimize latency when writing small files. 

Best regards,
Michal

**Comment by mirobers** [comment]
All of the blob upload methods set the metadata and properties on the blob, so no additional call to uploadMetadata is needed.
