### ISSUE TITLE
 java.lang.NoClassDefFoundError for azure storage

### ISSUE THREAD

**Issue by mayong1030** [Azure/azure-storage-java#246]
when we use azure-storage-5.0.0.jar in red linux.  we find  java.lang.NoClassDefFoundError error.
-------------------------------linux-----------------------------------------------
[shield@DalianTest ~]$ ./download.sh
+ PATH=.:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/shield/.local/bin:/home/shield/bin::/bin
+ export PATH
+ CLASSPATH=/home/shield/lib/logdownload.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar:/home/shield/lib/log4j-core-2.7.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar:/home/shield/lib/log4j-core-2.7.jar:/home/shield/lib/azure-storage-5.0.0.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar:/home/shield/lib/log4j-core-2.7.jar:/home/shield/lib/azure-storage-5.0.0.jar:/home/shield/lib/jackson-core-2.8.10.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar:/home/shield/lib/log4j-core-2.7.jar:/home/shield/lib/azure-storage-5.0.0.jar:/home/shield/lib/jackson-core-2.8.10.jar:/home/shield/lib/camel-ftp-2.20.1.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar:/home/shield/lib/log4j-core-2.7.jar:/home/shield/lib/azure-storage-5.0.0.jar:/home/shield/lib/jackson-core-2.8.10.jar:/home/shield/lib/camel-ftp-2.20.1.jar:/home/shield/lib/camel-core-2.20.1.jar
+ export CLASSPATH
+ CLASSPATH=/home/shield/lib/logdownload.jar:/home/shield/lib/log4j-slf4j-impl-2.7.jar:/home/shield/lib/log4j-api-2.7.jar:/home/shield/lib/log4j-core-2.7.jar:/home/shield/lib/azure-storage-5.0.0.jar:/home/shield/lib/jackson-core-2.8.10.jar:/home/shield/lib/camel-ftp-2.20.1.jar:/home/shield/lib/camel-core-2.20.1.jar:/home/shield/lib/camel-core-2.20.1.jar
+ export CLASSPATH
+ CLASS=com.sony.log.analytics.LogDownLoadVisit
+ java com.sony.log.analytics.LogDownLoadVisit
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/azure/storage/StorageException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.microsoft.azure.storage.StorageException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

[shield@DalianTest ~]$ java -version
**openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)**
-------------------------------linux-----------------------------------------------

in windows, i can use azure-storage-5.0.0.jar without error.

-------------------------------test.bat-----------------------------------------------
set path=.;%path%;%JAVA_HOME%;%JAVA_HOME%\bin;
set classpath=.;%classpath%;

set classpath=%classpath%.\lib\logdownload.jar;
set classpath=%classpath%.\lib\azure-storage-5.0.0.jar;
set classpath=%classpath%.\lib\camel-core-2.20.1.jar;
set classpath=%classpath%.\lib\camel-ftp-2.20.1.jar;
set classpath=%classpath%.\lib\jackson-core-2.8.10.jar;
set classpath=%classpath%.\lib\log4j-api-2.7.jar;
set classpath=%classpath%.\lib\log4j-core-2.7.jar;
set classpath=%classpath%.\lib\log4j-slf4j-impl-2.7.jar;

%JAVA_HOME%\bin\java com.sony.log.analytics.LogDownLoadVisit

-------------------------------test.bat-----------------------------------------------

Is there anything to be noticed for azure-storage-5.0.0 in linux? can we use OpenJDK ?

**Comment by mayong1030** [comment]
i have fixed

**Comment by rhodium289** [comment]
Good news. How did you fix it? What was the issue?

**Comment by rupesh3020** [comment]
@mayong1030 you should atleast put the solution when you have fixed.
