### ISSUE TITLE
Storage invents extra characters when ading a base64 encode string in a JSON file to blob storage

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-storage-java#250]
Pushing a JSON file with a base64 encoded image  works fine. I do not invents extra characters. If I retrieve the file again two extra \u003d characters are added to every base64 encoded string

Workaround:
```
final String untaintedJson = json.replaceAll("\u003d", "").intern();
    if (!json.equals(untaintedJson)) {.. moan in log
```

**Comment by mirobers** [comment]
This would be two equals signs: `==`. It it typical to find these at the end of base64 encoded strings as padding to make an even number of bytes. The upload path does not interpret the contents of a blob and certainly would not detect and modify base64 strings. So I strongly suspect the equals signs are being added as a result of base64 conversion somewhere in your own code.

If this doesn't help, please provide some repro code and we'll take a look.

**Comment by nicenemo** [comment]
Was a failure on our side
