### ISSUE TITLE
Unable to set local interface IP on outgoing Azure connections.

### ISSUE THREAD

**Issue by sowmya-manjanatha** [Azure/azure-storage-java#27]
Our product is configured to route traffic out of multiple VLAN networks.  We would like to connect to the Azure cloud using a specific network.  It appears that at this point in time the Azure-storage-java SDK does not expose the ability to set the source IP on outgoing Azure connections.

**Comment by emgerner-msft** [comment]
Sorry for lack of response on this.

While it doesn't appear to be added in the dependency list in the pom, this pull request adds a dependency on Apache HttpClient. We're not comfortable taking this additional dependency at this point in time. It also looks like code was potentially copied from both OpenJDK and the Apache lib itself which we are similarly not comfortable with.

I'm going to close the pull request, but if you have other ideas as to how to accomplish what you need in our lib without the above concerns we're happy to discuss other options on this thread.

**Comment by emgerner-msft** [comment]
Closing as we haven't heard anything. Please reopen if you'd like to discuss further.
