### ISSUE TITLE
New versions not compatible with hadoop-azure module

### ISSUE THREAD

**Issue by dromard** [Azure/azure-storage-java#276]
New versions of azure storage are not compatible with hadoop-azure, which implies that there is no support of the java hadoop library with azure blob storage. See hadoop-azure module https://hadoop.apache.org/docs/current/hadoop-azure/index.html

This implies that to link hdfs with the azure storage, we must use the azure storage 2.0.0 which is quite outdated. Would it be possible to take in consideration the hadoop azure storage while creating the new versions of the azure-storage ?

**Comment by rickle-msft** [comment]
Hi, @dromard. We encourage you to check out v12 of this project which has an artifact called azure-storage-file-datalake that supports HDFS apis. We would love for your feedback on this addition. I am going to close this issue now as the customer request has been met, but please feel free to reopen it if there are further concerns.
