### ISSUE TITLE
Class CloudBlockBlobTests depends on features available only in Java 9

### ISSUE THREAD

**Issue by terifan** [Azure/azure-storage-java#282]
Method InputStream.readAllBytes() was implemented in Java 9

**Comment by rickle-msft** [comment]
This should be fixed here: https://github.com/Azure/azure-storage-java/commit/4db58fb4c3ab59e4188a8f0b86119b7ce2c44b63#diff-7f692f7a94e98c174f21dbd84c396c32R1037
