### ISSUE TITLE
Unable to Mock POJOs in com.microsoft.azure.storage.blob package

### ISSUE THREAD

**Issue by 64BitChris** [Azure/azure-storage-java#29]
When writing an application that uses this library, I am unable to create POJO objects for testing.  In particular, I can not instantiate a BlobProperties object and set the eTag property.

I am unable to mock/extend the class as it's final - this is fine, however I can not call BlobProperties.setETag()/BlobProperties.setLastModified() due to the fact that it is protected.  I attempted to place a builder in the same package so that I can call these methods, but since the jar has been signed, I can't load classes in this package that aren't in this jar.  I have to resort to reflection in order to set these values, which is tedious and cumbersome.

In addition, if the intent is for only classes within that package to have access, then the proper access level should be package-protected/default rather than 'protected' (as there can be no subclasses due to the finality, this is effectively the current state).

If this client is to be widely used, it should be flexible enough to allow for people to be able to work with the POJOs with little friction (the S3 library doesn't have these snags).  I can see of at least four ways of doing this:

1. Release an unsigned jar where we can place our custom objects/builders in the same package.  I've never seen an open source library where I couldn't place a new class in the package in order to gain access to protected members so this may be an unintended side effect of the way we're signing the jar.
2. Change the POJO accessors to public so that they can be manipulated outside the package.
3. Remove the final keyword from each POJO and allow extensibility.
4. Add Builders/Constructors for each POJO (this will add a lot of boilerplate code though).

Probably one of steps 1-3 would be cleanest to implement.  If there's agreement on how to best fix this, I can make the changes and submit a PR.

**Comment by kervinpierre** [comment]
I need BlobProperties.setLastModified() to be public so we can implement a 'touch /path/to/file' feature.

Why protect that API call when the user has write permissions on the file in question?

**Comment by esummers-msft** [comment]
The lastModified property on a blob represents the time that the service last saw a change made to that blob.  The easiest way to update it to the current time (without changing the blob) is to use the uploadProperties() or uploadMetadata() methods on a blob.  This is why the code snippet you provided works.  When the client makes a call to uploadProperties() the service updates the lastModified value it has stored to the current time.  The snippet would still work if the call to setLastModified() were removed.  Making setLastModified() public would not help as uploadProperties() does not even send lastModified to the service.
 
Additionally, we do not recommend using reflection on our APIs .  Future versions may make signature changes to non-public methods. This would break code using them this way.
 
Below is a modified version of the code you provided which still updates lastModified() :
 
    CloudBlockBlob currBlob = currContainer.getBlockBlobReference("/some/path");
    currBlob.downloadAttributes();
    currBlob.uploadProperties();

**Comment by emgerner-msft** [comment]
Looks like Eric addressed your particular issue with last modified time, and we've verified internally and with a customer per issue #77 that PowerMock works with our library for more general mocking needs.
