### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-storage-java#302]
Adding support for specifying a callback to process progress notifications on download and upload.

**Comment by yeroc** [comment]
It looks like this is exposed in the SDK but not implemented?  At least the `TransferManager` accepts implementations of `IProgressReceiver` for uploads and downloads via `TransferManagerUploadToBlockBlobOptions` and `TransferManagerDownloadFromBlobOptions`.  It's misleading to have these as options without actually having it implemented.  Is there an ETA on getting this fixed?

Thanks,
Corey

**Comment by rickle-msft** [comment]
Yes this was in oversight in some of our GA preparation as we thought we would have time to add it before GA and then neglected to remove it when we realized we couldn't add it in time. I apologize that this mistake caused a poor experience for you. I am hoping to add support for it in the next release, which is scheduled for about the middle of October.

**Comment by yeroc** [comment]
Thanks for the update @rickle-msft.

**Comment by rickle-msft** [comment]
Hi, @yeroc. FYI, this feature has been merged into dev and so  is confirmed for our upcoming release. I am going to close this issue, as I believe the feature is complete and your concerns are addressed, but if you have any further comments or questions, please feel free to reopen or post again.
