### ISSUE TITLE
Support metadata for CloudQueueMessages

### ISSUE THREAD

**Issue by gjong** [Azure/azure-storage-java#306]
In a large scale application where data flows through various applications using events (CloudQueueMessage) in the Azure Storage Queue it would be really nice to have some additional metadata that can be put in each message. 

The main use case for us would be to flag messages with a Correlation ID so multiple messages belonging to one source event can be traced through the system. I know that a CloudQueueMessage currently supports an ID, but believe that it is generated by the Azure Storage system itself. So this ID is useless if you need to track an event that flows through multiple applications using Azure Storage Queues.

Is there any way of adding custom metadata (or properties like with the eventhub) to add additional information you do not want to be part of the message body?

**Comment by rickle-msft** [comment]
Hi! Thank you for your message! This would require support on the Azure Storage service itself, beyond just the client libraries. I have logged this as a feature request in their tracker for you. I'm closing this issue as this is not a good place to track service features.
