### ISSUE TITLE
Connecting HTTP Proxy with authentication over HTTPS

### ISSUE THREAD

**Issue by daniel2005315** [Azure/azure-storage-java#307]
For now, we are able to set the http proxy without authentication inside OperationContext, by doing something like:

`oc.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)));`

However, this cannot be done with a proxy connection which requires authentication, and passing in authorization header over https will not work, for instance:
https://stackoverflow.com/questions/34877470/basic-proxy-authentication-for-https-urls-returns-http-1-0-407-proxy-authenticat

I know that by setting up a default authenticator  in java will do the job but it is not an option for me in my scenario.

Is there anyway for me to establish a HTTP Proxy with authentication over HTTPS?

**Comment by rickle-msft** [comment]
Hi, @daniel2005315. I am sorry this issue seems to have slipped through the cracks. Have you made any progress on this or do you still need support?

**Comment by marlinspike** [comment]
My customer environment requires communication with various servers over HTTPS, including the Azure storage endpoint. We have to use different SSL contexts since the validation logic is different for each. So, we can just set the default SSL context of the JVM, since that’s a system wide change that will have wide ranging impacts.

We’d like to be able to create isolated SSL configurations for connecting to the Azure service endpoint.
My customer can already do this with the AWS SDK, and we’d like to be able to support that with the Azure Java SDK as well.

**Comment by rickle-msft** [comment]
Hi, @marlinspike. Thank you for contributing to this thread. I have to admit I am no expert on SSL and HTTPS. Can you please share some more details on what your ideal experience would be, whether it's setting some properties on the operation context, another api, etc? Any more information you can share on SSL contexts would also be very helpful. Finally, have you checked to see if this works in the async SDK (v10.0.0+)?

**Comment by marlinspike** [comment]
Hello @rickle-msft. So the current v10 SDK lets you support http proxies, but for my customer's purposes, that request must be over http and we need to customer provided certs. We need to be able to set the SSLContext for the client, so that we're only affecting this particular client and not the JVM.

The AWS SDK already allows you to do this. We'd like to be able to provide the same experience to our customer.

Here's what it would ideally look like:

`        @Override
        public void run(String... args) {        
                NettyClient.Factory factory = new NettyClient.Factory(new Bootstrap().resolver(new MyResolverGroup()), 100, 100);              
                factory.sslContext(SslContextBuilder.forClient().trustManager(new File("atruststorepath.pem")).build());
                
                HttpPipelineBuilder httpPipelineBuilder = new  HttpPipelineBuilder();
                httpPipelineBuilder.withHttpClient(factory.create(new HttpClientConfiguration(null)));
                
                BlockBlobURL blockBlobURL = new BlockBlobURL(new URL("bob.azure.com"), httpPipelineBuilder.build());
        }

        public static class MyResolverGroup extends AddressResolverGroup<InetSocketAddress> {

            public static final MyResolverGroup INSTANCE = new MyResolverGroup();
            @Override
            protected AddressResolver<InetSocketAddress> newResolver(EventExecutor executor) throws Exception {
                return new MyResolver(executor).asAddressResolver();
            }
        }
        
        public static class MyResolver extends InetNameResolver {
            public MyResolver(EventExecutor executor) {
                super(executor);
            }
            @Override
            protected void doResolve(String inetHost, Promise<InetAddress> promise) throws Exception {
                try {
                if(inetHost.contains("azure.com")) {
                        promise.setSuccess(SocketUtils.addressByName("foo.bar.customer.proxy.endpoint.com"));
                } else {
                        promise.setSuccess(SocketUtils.addressByName(inetHost));
                }
                } catch (UnknownHostException e) {
                    promise.setFailure(e);
                }
            }
            @Override
            protected void doResolveAll(String inetHost, Promise<List<InetAddress>> promise) throws Exception {
               //TODO
            }
`

**Comment by marlinspike** [comment]
@rickle-msft, any updates?

**Comment by rickle-msft** [comment]
Hi, @marlinspike. My apologies. I didn't see your latest comment until just now, so thank you for checking in. Could I actually ask you to post this issue on [this repo](https://github.com/Azure/autorest-clientruntime-for-java) and probably link this discussion over there, too? I'm sorry to redirect you, but the autorest runtime library actually owns the NettyClient and proxy support, so they will be able to better address your question.

**Comment by rickle-msft** [comment]
@marlinspike Were you able to get an adequate resolution on the runtime repo or should we follow up with them on our end?

**Comment by rickle-msft** [comment]
I am going to close this issue as it has been inactive for a while and because proxy support has been reworked in v12. Please let us know if you are still experiencing this issue in v12.

**Comment by mcbeanc** [comment]
@Rickle-msft,  Was "**OperationContext**" replace with something else in v12?

**Comment by rickle-msft** [comment]
@mcbeanc The fields and operations provided by OperationContext, if they are still present, have been reorganized into different locations. Is there something in particular in the OperationContext you are looking for? That will help give you a more specific response.

**Comment by mcbeanc** [comment]
@rickle-msft I have to go through a proxy server to communicate with azure resources.  Here's a snippet of code:
private OperationContext configureOperationContext() {
		OperationContext opContext = new OperationContext();
		if (this.isUseProxy()) {
			Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(
					this.getProxyHost(), this.getProxyPort()));
			opContext.setProxy(proxy);
		}
		return opContext;
	}

The  OperationContext class was in com.microsoft.windowsazure.services.core.storage for v8.6 and I can only find it in com.microsoft.windowsazure.services.core.storage.

**Comment by rickle-msft** [comment]
@mcbeanc Setting a proxy is now done directly on the httpClient when configuring a builder for a client type. The best example I can offer is in our [test setup](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/APISpec.groovy#L402). There's a little more there than you might need, but the crux of it is getting the httpClient builder, setting the proxy, and calling build. You can pass the result to the `httpClient` method on the storage client builder and you should be good to go.
