### ISSUE TITLE
API for gathering telemetry data for Azure Mem with Java SDK

### ISSUE THREAD

**Issue by AdityaTurbo** [Azure/azure-storage-java#321]
Hi

We are looking for a Java SDK based api which can provide multiple historical data points for Azure Memory. Currently we are using retrieve() method from https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/table/TableOperation.java but it provides single datapoint. 

Thanks,
Aditya

**Comment by asorrin-msft** [comment]
You can retrieve multiple entities from a table using a [Query](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-java#retrieve-all-entities-in-a-partition).  Is this what you're looking for?

**Comment by AdityaTurbo** [comment]
Thanks. This helps. 

Aditya
