### ISSUE TITLE
listContainer lists Containers and blob

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-storage-java#324]
I am not sure if this is something intentional or if it is a bug. When trying to list out the containers, without giving the root location, it also lists out blobs. For example:

```java
StorageCredentialsAccountAndKey accountAndKey = new StorageCredentialsAccountAndKey(this.accountName, this.accountKey);
CloudStorageAccount account = new CloudStorageAccount(accountAndKey, this.useHttps);

CloudBlobClient cloudBlobClient = account.createCloudBlobClient();
CloudBlobContainer cloudBlobContainer = cloudBlobClient.getContainerReference(this.containerName);

for (CloudBlobContainer blobItem : cloudBlobContainer.listContainers()) {
    System.out.println(blobItem.getName());
}
```

The above code prints out the container name and also the blob names that are **not** related to the container. See the image below:

![blo-container](https://user-images.githubusercontent.com/7360286/41519102-2fd971fe-731a-11e8-8342-76feaa1765db.JPG)

Any idea?

**Comment by mirobers** [comment]
This is a List Containers operation, which lists all containers in your account. This is (somewhat confusingly) available on the CloudBlobContainer object even though it operates at the service level. As you can see in [the code](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudBlobContainer.java#L1504), this just proxies the same API on CloudBlobClient. Use listBlobs() to get a list of blobs within the container.

**Comment by akshaybabloo** [comment]
Is there a way to get blobs and containers without combined list? Like listContainer lists only the container and not the blobs.

**Comment by mirobers** [comment]
listContainers only lists containers and listBlobs only lists blobs. You appear to have a container named "testblob", which might be causing some confusion.

**Comment by mirobers** [comment]
That code lists only containers. You have a container that you believe is a blob. You can double-check in Storage Explorer.

**Comment by akshaybabloo** [comment]
Ahhh.... Yes. I was looking at the public access level which showed Container and Blob 🤦‍♂️
