### ISSUE TITLE
Columns for table storage are created based on setters

### ISSUE THREAD

**Issue by nicenemo** [Azure/azure-storage-java#325]
When having a pojo with fields and only getters no columns
are created for the fields or getters. Only if I have a pojo that as setters fields are created.

We use [Lombok](https://projectlombok.org/) to generate getters and setters.
If `@Setter` is removed in the below sample code, then no columns are created in table storage.

## Sample code

```Java

@Getter
@Setter
public class Health extends TableServiceEntity {
  private String status;
  private String metrics;
  private final String service = "Some health service";

  public Health() {
    super("health", UUID.randomUUID().toString());
  }

  private static Health health(final String status, final HealthMetrics metrics) {
    final Health result = new Health();
    result.status = status;
    result.metrics = getGson().toJson(metrics, HealthMetrics.class);
    return result;
  }
}

```

## Expected 

Either:
* document that setters are required
* generate columns based on fields

**Comment by zezha-msft** [comment]
Hi @nicenemo, thanks for reaching out.

I've logged this issue for investigation.

**Comment by rickle-msft** [comment]
We have decided that we will update our documentation. Thank you again for your feedback. I will close this issue as I believe your concern is addressed and we are tracking this work in our backlog, but feel free to reopen it for further discussion as you see fit.
