### ISSUE TITLE
SDK v10 cannot find dependencies

### ISSUE THREAD

**Issue by rocketraman** [Azure/azure-storage-java#326]
When adding the SDK v10 to my app, the transitive dependencies include SNAPSHOT dependencies that do not exist in the usual public repos, specifically for `com.microsoft.azure.v2:autorest-clientruntime-for-java:2.0.0-SNAPSHOT`:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
     Required by:
         project : > com.microsoft.azure:azure-storage-blob:10.0.0-Preview
      > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
         > Could not parse POM https://nexus.myorg.com/repository/maven-public/com/microsoft/rest/v2/client-runtime/2.0.0-beta2/client-runtime-2.0.0-beta2.pom
            > Could not find com.microsoft.azure.v2:autorest-clientruntime-for-java:2.0.0-SNAPSHOT.
              Searched in the following locations:
                  file:/home/raman/.m2/repository/com/microsoft/azure/v2/autorest-clientruntime-for-java/2.0.0-SNAPSHOT/maven-metadata.xml
                  file:/home/raman/.m2/repository/com/microsoft/azure/v2/autorest-clientruntime-for-java/2.0.0-SNAPSHOT/autorest-clientruntime-for-java-2.0.0-SNAPSHOT.pom
                  file:/home/raman/.m2/repository/com/microsoft/azure/v2/autorest-clientruntime-for-java/2.0.0-SNAPSHOT/autorest-clientruntime-for-java-2.0.0-SNAPSHOT.jar
                  https://nexus.myorg.com/repository/maven-public/com/microsoft/azure/v2/autorest-clientruntime-for-java/2.0.0-SNAPSHOT/maven-metadata.xml
                  https://nexus.myorg.com/repository/maven-public/com/microsoft/azure/v2/autorest-clientruntime-for-java/2.0.0-SNAPSHOT/autorest-clientruntime-for-java-2.0.0-SNAPSHOT.pom
                  https://nexus.myorg.com/repository/maven-public/com/microsoft/azure/v2/autorest-clientruntime-for-java/2.0.0-SNAPSHOT/autorest-clientruntime-for-java-2.0.0-SNAPSHOT.jar
```

Here is the POM in question: http://search.maven.org/remotecontent?filepath=com/microsoft/rest/v2/client-runtime/2.0.0-beta2/client-runtime-2.0.0-beta2.pom -- it clearly contains a reference in its parent POM to the snapshot.

**Comment by rocketraman** [comment]
Furthermore, if I enable the sonatype oss snapshots repo, it still doesn't work:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
     Required by:
         project : > com.microsoft.azure:azure-storage-blob:10.0.0-Preview
      > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
         > inconsistent module metadata found. Descriptor: com.microsoft.rest.v2:client-runtime:2.0.0-SNAPSHOT Errors: bad version: expected='2.0.0-beta2' found='2.0.0-SNAPSHOT'
```

**Comment by rickle-msft** [comment]
Hi, Raman. Thank you for filing this issue and apologies for your inconvenience. I am investigating this now and will follow up with you when I have more information.

**Comment by RikkiGibson** [comment]
It looks like we goofed up in our publish process. To consume this version it's necessary to reference the Sonatype snapshot repository:

In Maven:
```xml
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
```

In Gradle:
```groovy
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
```

We'll work on getting a version out that doesn't have this issue very soon.

**Comment by rocketraman** [comment]
@RikkiGibson Actually that doesn't solve the problem -- gradle is able to download the snapshot, but still fails with another error which I reported @ https://github.com/Azure/autorest-clientruntime-for-java/issues/443:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
     Required by:
         project : > com.microsoft.azure:azure-storage-blob:10.0.0-Preview
      > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
         > inconsistent module metadata found. Descriptor: com.microsoft.rest.v2:client-runtime:2.0.0-SNAPSHOT Errors: bad version: expected='2.0.0-beta2' found='2.0.0-SNAPSHOT'
```

I was able to get it working by recompiling `com.microsoft.rest.v2:client-runtime:2.0.0-beta2` at this commit: https://github.com/Azure/autorest-clientruntime-for-java/tree/1a6797daba6783e7924e8bd0279afa641ae0746f.

However note that the tests appear to be broken at that commit -- I had to use `-DskipTests` to build it.

**Comment by RikkiGibson** [comment]
Thanks for letting us know.

**Comment by RikkiGibson** [comment]
[client-runtime-2.0.0-beta3](https://repo.maven.apache.org/maven2/com/microsoft/rest/v2/client-runtime/2.0.0-beta3/) is out. I think azure-storage-java-v10-preview can be updated to reference this and released soon. @rickle-msft

**Comment by rickle-msft** [comment]
Quick update: We are looking to add one more thing to the library before we release a new preview version, so we held off for one more week. We will release by the end of this week with or without that new feature to get the fix out in a reasonable time frame.

**Comment by rocketraman** [comment]
Thanks for the update. Looking forward to the new release.

**Comment by rickle-msft** [comment]
Version 10.0.1-Preview is out and should resolve this issue as well as bring in some additional changes and updates. Please take a look at your convenience. I will close this issue now, but feel free to reopen it if you have further questions or this issue persists.

Thank you for your feedback!
