### ISSUE TITLE
Operations sometimes hang because readTimeout of HttpURLConnection is hard coded to 0

### ISSUE THREAD

**Issue by james-hu** [Azure/azure-storage-java#33]
When HTTP keep-alive is enabled (by default it is), sometimes HTTP connections used by Azure storage Java client hang. Of course we can blame HTTP keep-alive to be not reliable, but if Azure storage Java client can set readTimeout of HttpURLConnection objects to a value other than zere this problem can be solved. Currently in com.microsoft.azure.storage.core.Utility.getRemainingTimeoutgetRemainingTimeout(...) it is implemented as:
            // represents an infinite timeout
            return 0;

**Comment by emgerner-msft** [comment]
Setting the readTimeout to non-0 is already possible via the options in CloudTableClient. If you look at the full body of the getRemainingTimeout method which you mention it only sets the timeout to infinite if the options.getOperationExpiryTimeInMs() it is passed is null. If you check out the docs for getOperationExpiryTimeInMs they say “Returns the time at which this operation expires. This is computed by adding the time the operation begins and the maximum execution time and will be null if maximum execution time is null. For more information about maximum execution time, see setMaximumExecutionTimeInMs”. So, if you set the maximum execution time to a non-null value, the readTimeout set on HttpURLConnection will be non-zero.

In a coming release we will be making the default 5 min rather than infinite for the HttpURLConnection readTimeout when maximumExecutionTime is not set. Setting maximumExecutionTime lower than 5 min will still cause an earlier timeout if that’s what you’re looking for.

**Comment by james-hu** [comment]
setOperationExpiryTimeInMs(...) is private so there is no way to set it.
getOperationExpiryTimeInMs() actually just returns whatever has been passed in to setOperationExpiryTimeInMs(...) disregarding the maximumExecutionTimeInMs.

So in reality, even if setMaximumExecutionTimeInMs(...) had been called, the options object will have a non-null maximumExecutionTimeInMs field and a null operationExpiryTime field.

Even if we can set operationExpiryTimeInMs, it is not a relative value (how long since when), it is an absolute value (milliseconds since epoch). Therefore there is no way to set a global default value in it.

```java
    /**
     * RESERVED FOR INTERNAL USE.
     * 
     * Returns the time at which this operation expires. This is computed by adding the time the operation begins and
     * the maximum execution time and will be null if maximum execution time is null. For more information about maximum
     * execution time, see {@link #setMaximumExecutionTimeInMs(Integer)}.
     * 
     * @param operationExpiryTime
     *            the operationExpiryTime to set
     */
    private void setOperationExpiryTimeInMs(final Long operationExpiryTime) {
        this.operationExpiryTime = operationExpiryTime;
    }

    /**
     * RESERVED FOR INTERNAL USE.
     * 
     * Returns the time at which this operation expires. This is computed by adding the time the operation begins and
     * the maximum execution time and will be null if maximum execution time is null. For more information about maximum
     * execution time, see {@link #setMaximumExecutionTimeInMs(Integer)}.
     * 
     * @return The current operation expiry time, in milliseconds, for this request.
     */
    public Long getOperationExpiryTimeInMs() {
        return this.operationExpiryTime;
    }

```

```java
    /**
     * Returns a value representing the remaining time before the operation expires. 0 represents an infinite timeout.
     * 
     * @param operationExpiryTimeInMs
     *            the time the request expires
     * @return the remaining time before the operation expires, or 0 to represent an infinite timeout
     * @throws StorageException
     *             wraps a TimeoutException if there is no more time remaining
     */
    public static int getRemainingTimeout(Long operationExpiryTimeInMs) throws StorageException {
        if (operationExpiryTimeInMs != null) {
            long remainingTime = operationExpiryTimeInMs - new Date().getTime();
            if (remainingTime > Integer.MAX_VALUE) {
                return Integer.MAX_VALUE;
            }
            else if (remainingTime > 0) {
                return (int) remainingTime;
            }
            else {
                TimeoutException timeoutException = new TimeoutException(SR.MAXIMUM_EXECUTION_TIMEOUT_EXCEPTION);
                StorageException translatedException = new StorageException(
                        StorageErrorCodeStrings.OPERATION_TIMED_OUT, SR.MAXIMUM_EXECUTION_TIMEOUT_EXCEPTION,
                        Constants.HeaderConstants.HTTP_UNUSED_306, null, timeoutException);
                throw translatedException;
            }
        }
        else {
            // represents an infinite timeout
            return 0;
        }
    }
```

**Comment by emgerner-msft** [comment]
We are aware that setOperationExpiryTimeInMs is not publicly settable. If you look at the documentation for getOperationExpiryTimeInMs (which is a public method) you'll see that changing maximum execution time changes this value. Therefore, if you use setMaximumExecutionTimeInMs you'll see a non-negative readTimeout.

**Comment by james-hu** [comment]
According to the code (I posted above), setMaximumExecutionTimeInMs(...) is not able to change the return value of getOperationExpiryTimeInMs(). I confirmed this by setting break point in BaseRequest.createURLConnection(...). See the screenshot below for the actual values:
![screen shot 2015-04-08 at 11 06 56 am](https://cloud.githubusercontent.com/assets/8565700/7037027/95adf898-dddf-11e4-9fc9-1772129e3223.png)
(in my test, I've set maximumExecutionTimeInMs to 30 seconds)

**Comment by emgerner-msft** [comment]
Which API is this on and how did you call it? Namely, could you provide repro code? I've done a very simple repro test with a break point in BaseRequest and am seeing operationExpiryTime populated and readTimeout being set. Code below (you'd need to setup a container)

        BlobRequestOptions options = new BlobRequestOptions();
        options.setMaximumExecutionTimeInMs(5000);
        this.container.create(options, null);

**Comment by emgerner-msft** [comment]
Is this in table? It looks like that's true from your screen shot, but a confirmation would be good. If so, I might see the issue.

**Comment by james-hu** [comment]
Yes, table. Not sure whether it exists in queue or not.
```java
			storageAccount = CloudStorageAccount.parse(storageConnectionString);
			CloudTableClient tableClient = storageAccount.createCloudTableClient();
			CloudQueueClient queueClient = storageAccount.createCloudQueueClient();
			tableClient.getDefaultRequestOptions().setTimeoutIntervalInMs(AZURE_SERVER_TIME_OUT);
			tableClient.getDefaultRequestOptions().setMaximumExecutionTimeInMs(AZURE_EXECUTION_TIME_OUT);
```
![1](https://cloud.githubusercontent.com/assets/8565700/7037278/72607092-dde3-11e4-967d-bde6d681c8ec.png)
![2](https://cloud.githubusercontent.com/assets/8565700/7037281/7840d3f8-dde3-11e4-9b34-ab62c00814f8.png)

**Comment by emgerner-msft** [comment]
Ah yep, this looks be specific to non-blob which is why we got conflicting results with our repro code. :) What I said above should stand true - setting maximum execution time SHOULD set operation expiry and thus readTimeout but right now in table there's an issue where it doesn't. We will fix this in the next release along with setting the default readTimeout to 5 min rather than infinite. Thanks for the detailed investigation! I'll update the thread when the release with the fix is out.

**Comment by james-hu** [comment]
That's great! Thanks.

BTW, I hope the support team had fed back this to the dev team but just want to make sure:

Because of the retry logic, sometimes this happens:
1) the SDK tries to insert a new entity to a table
2) time out on client side
3) succeeded on server side
4) the SDK automatically tries again (because the first try time out) to insert the same entity
5) the SDK receives a 409 conflict because the entity had been inserted in previous try
6) Got the 409 conflict response, the SDK report this error to the application code

From the application code's point of view, the insertion failed because an entity with the same partition/row keys already exists. But we know it is not the truth. The entity actually was successfully inserted. This is a false negative.

There is another scenario that a conflict actually happened between the to-be-inserted entity and an already-exists entity. This is a true negative.

The problem is, there is no way for the application code to distinguish false negative and true negative. 

The suggestion from the support team is that we can disable the retry logic in SDK. But I know this can probably be solved inside the SDK. So I asked them to forward this to the dev/product team.

I hope this had already been recorded in the enhancement backlog.

**Comment by emgerner-msft** [comment]
I am a member of the dev team, so I'll just respond directly. For the exact reason you mention (there is no way for the application code to distinguish false negative and true negative), there is also no way for the SDK to differentiate. The same as you, we don't know whether the request that timed out was a successful insert or a conflict. So, we can't make the retry policy any more intelligent than it already is - it just has to fail.

One thing you could do for this specific scenario is leave the retry logic on and create an OperationContext object to send with your insert request. If a 409 is thrown, in the catch(StorageException ex) you can use the getRequestResults method of OperationContext to view details about the requests that were made. If you see a timeout followed by a conflict you can do a retrieve of the entity you've attempted to insert and check if it's equivalent. If it is, you can ignore the exception and continue as the table entity is equivalent to what you want. If it is different, you can assume the conflict is valid and handle it as you see fit.

**Comment by james-hu** [comment]
Even by doing this you still can't know whether the entity was inserted by yourself (false negative) or another user (true negative). A better way is to specify a random etag value when inserting, then if there is a conflict after timeout, read the entity back with minimal properties and compare the etag values. Since the timeout-then-conflict usually only happens when the server is relocating the partition (I guess) the overhead of this additional read-back-and-compare should be acceptable for most applications.

However this is the situation that most of the applications need to face, even if the workaround is not perfect, it would be good to include it in the SDK (maybe as an option controlled by a flag) rather than having the similar logic implemented by different developers in different applications, or implemented as an unofficial "plugin" to the SDK.

And, thanks for your explanations. It is really a good experience to have this kind of conversations.

**Comment by emgerner-msft** [comment]
As of our 2.2.0 release, the maximum execution time issue should be resolved and a default of 5 min is set for the readTimeout if neither maximum execution time or server timeout is set. This should resolve the original issue. Feel free to open additional issues if you would like to discuss other changes. Thanks!
