### ISSUE TITLE
How to write Application Log to the Azure Storage

### ISSUE THREAD

**Issue by 7000014349** [Azure/azure-storage-java#333]
I want to use java and Logback components to write the Application Log to the Azure Storage
My web application is deployed to the Azure platform
How can I realize it

**Comment by zezha-msft** [comment]
Hi @7000014349, [append blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs) would suit your needs well.
