### ISSUE TITLE
writeLength in BlobOutputStream, what is it?

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-storage-java#335]
What exactly is the `writeLength`? Is it byte size of the InputStream or something else?

https://github.com/Azure/azure-storage-java/blob/5e29fb94028e78d3a870c3d691239248993f932e/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/BlobOutputStream.java#L91

**Comment by rickle-msft** [comment]
Yes, it is the number of bytes to write. See here fore an example:

https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/GenericTests.java#L101

**Comment by akshaybabloo** [comment]
Thanks @rickle-msft
