### ISSUE TITLE
SAS tokens with missing optional parameters fail auth

### ISSUE THREAD

**Issue by lrdcasimir** [Azure/azure-storage-java#354]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

v10.0.1-Preview

### What problem was encountered?

SAS tokens include the string "null" in the string to sign for unset parameters which causes the signature to fail authentication.

### Have you found a mitigation/solution?

Locally, altering the canonical string to sign implementation to the form:
```
this.identifier == null ? "" : this.identifier
```
for optional parameters resolves the issue. I'll add tests for the implementation and follow up with a pull request.

**Comment by lrdcasimir** [comment]
Thanks @rickle-msft I suspect AccountSASSignatureValues has the same issues. I'll tackle it and tests this morning and see if I can have a PR for the issue today. Thanks.

**Comment by rickle-msft** [comment]
This has been resolved by #357 .
