### ISSUE TITLE
Example to copy disk from region-1 to region-2

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-storage-java#355]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10-async

### What problem was encountered?
Need a sample program to show how a disk can be copied from storage-1 (region-1) to storage-2 (region-2)

### Have you found a mitigation/solution?
No

**Comment by puneet101** [comment]
Don't see an example using the new async SDK

**Comment by puneet101** [comment]
Something like this but with java:
https://docs.microsoft.com/en-us/azure/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-managed-disks-to-same-or-different-subscription

**Comment by puneet101** [comment]
For example, it will be nice to have a few samples to illustrate how "az copy" would be implemented using the new SDK.

az storage blob copy start

Copy
az storage blob copy start --destination-blob
                           --destination-container
                           [--account-key]
                           [--account-name]
                           [--connection-string]
                           [--destination-if-match]
                           [--destination-if-modified-since]
                           [--destination-if-none-match]
                           [--destination-if-unmodified-since]
                           [--destination-lease-id]
                           [--metadata]
                           [--sas-token]
                           [--source-account-key]
                           [--source-account-name]
                           [--source-blob]
                           [--source-container]
                           [--source-if-match]
                           [--source-if-modified-since]
                           [--source-if-none-match]
                           [--source-if-unmodified-since]
                           [--source-lease-id]
                           [--source-path]
                           [--source-sas]
                           [--source-share]
                           [--source-snapshot]
                           [--source-uri]
                           [--timeout]

**Comment by puneet101** [comment]
Thanks @rickle-msft!

We are planning to support migration of both unmanaged and managed disks. Is there a sample for managed-disks also? High level idea is to move a virtual desktop from region-1 to region-2. The desktop could be using managed disks also.

**Comment by rickle-msft** [comment]
@puneet101 I believe the functionality you're looking for regarding managed disks is in this repo [here](https://github.com/Azure/azure-libraries-for-java). The README mentions that the compute libraries offer control over managed disks.

**Comment by rickle-msft** [comment]
I believe all parts of your question have been addressed, so I am going to close this issue now, but please feel free to re-open it if you have further questions or concerns.
