### ISSUE TITLE
The "Storage API doc page" link in README.md returns a 404

### ISSUE THREAD

**Issue by dennyac** [Azure/azure-storage-java#359]
The [Storage API doc page](https://docs.microsoft.com/en-us/java/api/storage/client?view=azure-java-preview) link in README.md returns a 404

**Comment by rickle-msft** [comment]
Hi, @dennyac. Thank you for alerting us to this! Can you please point me to which text links to this in the README?

**Comment by rickle-msft** [comment]
I think we found the one you are referring to. We are fixing it now. This is also the url that it should point to for your convenience.
https://docs.microsoft.com/en-us/java/api/overview/azure/storage/client?view=azure-java-preview
