### ISSUE TITLE
cannot disable TCP Nagle in java client

### ISSUE THREAD

**Issue by mogliang** [Azure/azure-storage-java#36]
Hi,

I used azure storage queue, and find there is huge performance difference (4x) between enable and disable TCP nagle (using C#)

My goal is using Java environment, so need find option do disable Tcp Nagle. However, i cannot find a way to do so in java storage lib.

Would you please guide me how to do this?

**Comment by mogliang** [comment]
Add some finding here.
---
in Java Environment, there isn’t a global switch to control TCP Nagle behavior. To turn off Nagle, the only way is set “setTcpNoDelay” method on Socket object.
 
Azure storage java library use java default HTTP library (Java.net). Unfortunately, this library wraps the socket object, but doesn’t expose ‘setTcpNoDelay’ method. Therefore, there is no way to disable Nagle in azure storage library.
 
To allow disable Nagle, one way is replace Java.net module with Apache HttpClient .
---

Since Nagle has big impact to the performance, would you consider add this feature?

**Comment by mogliang** [comment]
We created the java sample code, we find 10 threads can eat up all CPU resources, and throughput is about 100TPS. 

Sample code:
https://gist.github.com/mogliang/40bdee18d9ab1967aea7

By checking thread dumps, we found that application took most CPU time on serialization.

at javax.xml.stream.XMLOutputFactory.newInstance(Unknown Source)
at com.microsoft.azure.storage.queue.QueueMessageSerializer.generateMessageRequestBody(QueueMessageSerializer.java:50)
at com.microsoft.azure.storage.queue.CloudQueue.addMessageImpl(CloudQueue.java:293)
at com.microsoft.azure.storage.queue.CloudQueue.addMessage(CloudQueue.java:283)
at com.microsoft.azure.storage.queue.CloudQueue.addMessage(CloudQueue.java:230)
at QueueTestThread.run(Program.java:71)

we found that XMLOutputFactory creation is a very heavy operation, it took lots of CPU time, and shall be responsible for the high CPU and low throughput issue.

To mitigate this issue, we can simply make XMLOutputFactory as static object and create only once.

I created a pull request
https://github.com/Azure/azure-storage-java/pull/37

Thanks,

**Comment by emgerner-msft** [comment]
Thanks for the suggestions and your detailed investigation! Feel free to spin up additional issues separate from the Nagle thread if you find that easier.

We will evaluate changes to our use of XMLOutputFactory for a future release. As we use it throughout the library, we'd like to thoroughly investigate the issue.

Similarly, we recognize that it would be good to be able to disable Nagle and are evaluating options. We will update the thread at a later date when we have more information to share.

Thanks,
Emily

**Comment by emgerner-msft** [comment]
Per your suggestion, XMLOutputFactory is created a single time as a static object as of version 2.1. We wanted to fix it across the library rather than just in CloudQueue.addMessage so I will be closing your pull request. Thank you again for your investigation and contribution!
