### ISSUE TITLE
Dependency on javafx

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-storage-java#367]
The TransferManager imports the javafx package, which is not supported in the OpenJDK. As this is an internal-only implementation detail, we can remove this dependency without a breaking change.

**Comment by yeroc** [comment]
As noted this is a barrier not only to using OpenJDK but also Java 11 where JavaFX is no longer bundled with OracleJDK either.

**Comment by rickle-msft** [comment]
Hi, @yeroc . You can see that a [commit](https://github.com/Azure/azure-storage-java/commit/c362ce776cb661072a56c60b817d7a5d06892b96) with this fix has been checked into our dev branch and so is confirmed for our next release. I am going to close this issue now as I believe it has been addressed, but please feel free to reopen it or post again as you see fit.
