### ISSUE TITLE
When do you plan to support queues in SDK v10? 

### ISSUE THREAD

**Issue by darewreck54** [Azure/azure-storage-java#368]
It looks like SDK v10 only support blob storage.  When do you plan to support queues as well?

Thanks,
Derek

**Comment by rickle-msft** [comment]
You are correct. We are gearing up for a preview release of the queues SDK. Without any formal promise, I would estimate that release is out middle of October. Queues should also be able to transition to GA much quicker, too.

**Comment by rickle-msft** [comment]
One more update @darewreck54. We have published the code to GitHub [here](https://github.com/Azure/azure-storage-java/tree/New-Storage-SDK-V10-Preview). It is (clearly) still in preview, but it's out and ready to use! I am going to close this issue now that we have shipped the queues library, but if you have any further questions, please feel free to reopen this issue or a file a new issue.

**Comment by darewreck54** [comment]
@rickle-msft Thanks!  What is the ETA for supporting

- Tables
- Service Bus Queues

Thanks,
Derek
