### ISSUE TITLE
Question - Microsoft Azure Storage SDK for java V10 Max Connections

### ISSUE THREAD

**Issue by Melozzola** [Azure/azure-storage-java#375]
I'm using the Microsoft Azure Storage SDK for java and the specific artifact coordinates are:
`com.microsoft.azure:azure-storage-blob:10.1.0`

My use case is to stream incoming uploads from my server to Azure via the Azure Client provided by the library:

`[Client] ---upload---> [My Server] ---put object---> [Azure]`

What I would like to know is how many concurrent connections the Azure Client can handle and if the value is configurable?

I did try to configure the `channelPoolSize` in the following way:

    final NettyClient.Factory factory = new NettyClient.Factory(
             new Bootstrap(),
             0,
             10000); //<--- channelPoolSize
    final HttpClient client = factory.create(null);

    final PipelineOptions pipelineOptions = new PipelineOptions()
            .withLogger(new Slf4jLogger(LOG))
            .withRequestRetryOptions(NO_RETRY)
            .withClient(client);

    final HttpPipeline pipeline = StorageURL.createPipeline(credential, pipelineOptions);
    final URL endpoint = endpointForAccountOrThrow(accountName);
    final ServiceURL serviceURL = new ServiceURL(endpoint, pipeline);
    containerURL = serviceURL.createContainerURL(containerName);

But what I can see is that around 250 concurrent uploads the client starts failing with:

`
java.util.concurrent.TimeoutException: null
    at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.run(SingleTimeout.java:115)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
`

Any idea?

**Comment by Melozzola** [comment]
Hello, I found the problem and I share it here in case it is useful for somebody else.
The issue was that as the users number was growing, the streaming time was becoming higher and higher.
Around 250 concurrent uploads, there were requests taking more than 1 minute, but I had a generic retry policy defined as follows:

`
private static RequestRetryOptions NO_RETRY = new RequestRetryOptions(
            RetryPolicyType.EXPONENTIAL,
            1,
            null,
            null,
            null,
            null);
`

This kind of policy is forcing the request to be completed within a minute (which is the default tryTimeout).

After reading the java doc of `RequestRetryOptions`:

`
     * @param tryTimeout
     *      Indicates the maximum time allowed for any single try of an HTTP request. A value of {@code null} means that
     *      you accept our default. NOTE: When transferring large amounts of data, the default TryTimeout will probably
     *      not be sufficient. You should override this value based on the bandwidth available to the host machine and
     *      proximity to the Storage service. A good starting point may be something like (60 seconds per MB of
     *      anticipated-payload-size).
`

I switched to a per-request re-try policy setting the tryTimeout value based on the content size.
This solved my problem

**Comment by cuongvomanh** [comment]
> Hello, I found the problem and I share it here in case it is useful for somebody else.
> The issue was that as the users number was growing, the streaming time was becoming higher and higher.
> Around 250 concurrent uploads, there were requests taking more than 1 minute, but I had a generic retry policy defined as follows:
> 
> `private static RequestRetryOptions NO_RETRY = new RequestRetryOptions( RetryPolicyType.EXPONENTIAL, 1, null, null, null, null);`
> 
> This kind of policy is forcing the request to be completed within a minute (which is the default tryTimeout).
> 
> After reading the java doc of `RequestRetryOptions`:
> 
> ```
>  * @param tryTimeout
>  *      Indicates the maximum time allowed for any single try of an HTTP request. A value of {@code null} means that
>  *      you accept our default. NOTE: When transferring large amounts of data, the default TryTimeout will probably
>  *      not be sufficient. You should override this value based on the bandwidth available to the host machine and
>  *      proximity to the Storage service. A good starting point may be something like (60 seconds per MB of
>  *      anticipated-payload-size).
> ```
> 
> I switched to a per-request re-try policy setting the tryTimeout value based on the content size.
> This solved my problem

Hi @Melozzola 
Could you pls share your code that fix this issues? 
Thank u
