### ISSUE TITLE
TransferManager upload file is timing out for file size 200MB

### ISSUE THREAD

**Issue by abhay-at-eagle** [Azure/azure-storage-java#377]
Hi , 

As I understand , TransferManager does not do chunking when file size is less or equal to 256MB. However I am not able to upload it without chunking as my network is slow. Is there any way to increase the timeout to large value ?

Regards,
Abhay

**Comment by abhay-at-eagle** [comment]
Thanks.

I just looked at the code of RequestRetryOptions, below code looks to be buggy. tryTimeout is of type Integer but its range is checked against Long range.

`        if (tryTimeout != null) {
            Utility.assertInBounds("tryTimeoutInMs", tryTimeout, 1, Long.MAX_VALUE);
            this.tryTimeout = tryTimeout;
        }
        else {
            this.tryTimeout = 60;
        }`

Can you clarify on what is the unit of tryTimeout, is it seconds or milliseconds ?

Regards,
Abhay

**Comment by rickle-msft** [comment]
Sorry for the confusion on that! Timeouts are in seconds. You can see how we implement the timeout [here](https://github.com/Azure/azure-storage-java/blob/master/src/main/java/com/microsoft/azure/storage/blob/RequestRetryFactory.java#L155), which pretty explicitly uses seconds. I'll work on getting that constructor code cleaned up.

**Comment by rickle-msft** [comment]
Hi, @abhay-at-eagle. Just so you know, our next breaking release, which is likely sometime in December, includes an option that will allow you to configure the maximum size of a single-shot-upload, so this should mitigate your issue. Keep an eye out for v11 for that.

**Comment by rickle-msft** [comment]
@abhay-at-eagle. I apologize for the long delay. We were just unblocked from making the necessary breaking release which includes this added feature: v11.0.0. I will close this issue now as I believe the feature request has been adequately addressed, but please feel to reopen it if the fix does not suit your needs.
