### ISSUE TITLE
Use storage account in different region has to manage endpoint manually

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-storage-java#388]
Suppose I already have `StorageAccount` got from ARM API. But when I want to use it in US and China region. I has to build connection string by myself by providing different endpoint.

**Comment by rickle-msft** [comment]
Hi, @warrenzhu25. Thank you for your question. Can you please provide some more details on your scenario? Which version of the library are you using and what exactly is contained in the StorageAccount given back by ARM?

**Comment by warrenzhu25** [comment]
I'm using `azure` with version 1.14.0. This issue is related with #289. I can only get `accountName` and `key` from `StorageAccount`. Could you provide a method to directly return connection string? And storage blob v10 seem doesn't need connection string, but still need to build blobURL as below:
```java
URL blobUrl = new URL(String.format(Locale.ROOT, "https://%s.blob.core.windows.net", storageAccount.name()));
```

If for `China`, I have to write something like:
```java
URL blobUrl = new URL(String.format(Locale.ROOT, "https://%s.blob.core.chinacloudapi.cn", storageAccount.name()));
```
Could you hide this url, just directly return `URL`?

**Comment by warrenzhu25** [comment]
Do you have plan to handle different region issue? As end user, I don't want to care the real endpoint since credential file should have already contained such info.

**Comment by pemari-msft** [comment]
Our intention is for the user to pass the fully qualified `url` for clarity.

**Comment by rickle-msft** [comment]
I am going to close this issue as it has been dormant for six months and the initial question seems to have been addressed. Please feel free to reopen the issue if there are further questions or concerns.
