### ISSUE TITLE
single quote in partition key causes merge to fail

### ISSUE THREAD

**Issue by james-hu** [Azure/azure-storage-java#39]
If the partition key contains a single quote ("'") in an entity extending TableServiceEntity, insertion would succeed but merging would fail.
Not sure whether this problem applies to row key.

**Comment by emgerner-msft** [comment]
This problem also applies to row key and is a bug on our end. We will fix this in an upcoming release. Thanks for reporting!

**Comment by james-hu** [comment]
Thanks for looking into it. I know it is caused by the keys are not encoded before sending to the server side. I had looked into the code. However, there is one good side-effect of this. When there are lots of non-ascii characters in the keys, the size of request sent to the server is quite small comparing to if they are URL encoded as we can see in the response message. In tests, I've seen responses (with echoed partition and row keys URL encoded in the headers and 204 no content status code) twice as large as the request (with partition and row keys unencoded). This is quite annoying in terms of performance and network traffic. In fact, I believe echoing back partition and row keys together with a 204 no content status code is a wrong design. Those information are useless and resource wasting.

So I suggest to just escape the "'" character rather than URL encode the whole string if possible.

**Comment by emgerner-msft** [comment]
The single quote encoding issue has been fixed in our 2.2.0 release. Feel free to open additional issues if you would like to discuss other changes. Thanks!
