### ISSUE TITLE
V10 SDK for tables and analytics?

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#393]
Is there a plan to release V10 SDK for tables and analytics in the near future? V10 has a lot of welcome changes and I would like to use it, but I need support for tables and analytics.

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Azure Tables and any client libraries for Tables have actually moved over to the CosmosDB team, so there are no plans to support them here. Similarly for Azure Analytics. You could try posting [here](https://github.com/Azure/azure-cosmosdb-java) for tables. I'm not sure of where the Analytics team keeps their repos if they have any unfortunately. 

I am going to close this issue as I believe it has been fully addressed, but if you have other questions or concerns, please feel free to reopen it or post again.

**Comment by SukruthKS** [comment]
Thanks for the info! 
I was actually referring to Storage Analytics. Version 8 of the storage SDK has support for getting metrics and storage logs using a class called 'CloudAnalyticsClient'. Will the support be added to V10?

**Comment by SukruthKS** [comment]
Thanks Rick! I rely on storage metrics for a critical scenario in my system and it'd be great if you could add the support for that in the SDK. Azure Monitor does not work well in my scenario as I'd need to have subscription/resource level permissions whereas I'm only privy to SAS tokens for the storage account.

**Comment by rickle-msft** [comment]
I see. Thank you for those details. I'll reopen this issue to track this feature request. I'll circle back when we it looks like we'll be able to take this.

**Comment by fhryo-msft** [comment]
As we advise in offline meeting, it's recommended to use Azure Monitor API to read metrics data. So I would suggest close this issue.

**Comment by fhryo-msft** [comment]
#please-close

**Comment by maltalex** [comment]
@rickle-msft  What about Azure Tables? The [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-java) still points to this SDK, the [samples](https://github.com/Azure-Samples/storage-table-java-getting-started) use this SDK, and the CosmosDB repo doesn't seem to contain a Table client.

**Comment by rickle-msft** [comment]
Hi, @maltalex. Any work related to tables has definitively moved to CosmosDB, so the Storage team unfortunately can't do much in the way of supporting tables. They own everything from documentation to client support to service features, even if that means their current story is just relying on old stuff for now. As I understand it, they should be working towards updating this story, but I can't guarantee that in any way. The best I can suggest is that you reach out to their team and be another voice asking for updated client support for tables. 

I am going to close this issue as was requested as it seems to me everything has been addressed, but please feel free to reach out or reopen the issues if there are further concerns.
