### ISSUE TITLE
Naming conflicts between V10 and V8

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-storage-java#400]
Some types have identical names and packages across v10 and V8 but are obviously used differently. The conflict makes it difficult if not impossible to load the versions side by side, making the upgrade story difficult. 

So far the only known types with this conflict are BlobListingDetails, ContainerListingDetails, and StorageException

**Comment by rykawagu** [comment]
Hi, I faced the same issue.
is there any workaround on this currently? i would appreciate it if you told me.

Thanks,

**Comment by rickle-msft** [comment]
Hi, @rykawagu. Can you give more details on what you experienced? From my investigation, only BlobListingDetails and ContainerListingDetails are the same type name in the same package (StorageException is actually in a different package in each). When I tested the ability to load side-by-side in a sample maven application, I actually didn't get any compiler errors. The only obstacle I found was that the first maven dependency listed determined which ListingDetails type I got.

**Comment by rickle-msft** [comment]
This was resolved in #403 and will be included in our next major version change.

**Comment by carlosbarragan** [comment]
We are also experiencing problems in a project where we use the Azure EventHostProcessor for consuming events. The EventHostProcessor SDK uses the old blob storage SDK (Version 8). In the same project we want to use the blob storage SDK version 10.  We got the following exception when starting the application:

`exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
 Location:
   com/microsoft/azure/eventprocessorhost/AzureStorageCheckpointLeaseManager.getAllLeases()Ljava/util/concurrent/CompletableFuture; @13: invokestatic
 Reason:
   Type 'com/microsoft/azure/storage/blob/BlobListingDetails' (current frame, stack[0]) is not assignable to 'java/lang/Enum'
 Current Frame:
   bci: @13
   flags: { }
   locals: { 'com/microsoft/azure/eventprocessorhost/AzureStorageCheckpointLeaseManager', null, 'java/util/ArrayList' }
   stack: { 'com/microsoft/azure/storage/blob/BlobListingDetails' }
 Bytecode:
   0000000: 014c bb00 7d59 b700 7e4d b200 7fb8 0080
   0000010: 4e2a b400 2712 0104 2d2a b400 0601 b600
   0000020: 703a 0419 042c ba00 8100 00b9 0082 0200
   0000030: 2cb8 0035 4ca7 0029 4db2 0048 2ab4 0015
   0000040: 1283 b600 612c b900 5c03 00bb 0041 59b7
   0000050: 0042 4c2b 2c12 79b8 0044 b600 4557 2bb0
   0000060:`

It seems that the EventHostProcessor picks up the `BlobListingDetails` class from the blob storage SDK 10, which is not an `enum` anymore, hence the above problem occurs, because the class cannot be assigned as an `enum`.

Additional information: We run our application in Docker with jdk10. 

When is the major version with the fix in #403  going to be released ?

**Comment by rickle-msft** [comment]
Hi, @carlosbarragan. Thanks for contributing to this discussion. This breaking release is going to be paired with the new service version, which is scheduled to come out in December. I can't make hard promises about that, but that's our target.

**Comment by carlosbarragan** [comment]
@rickle-msft thank you for answering. Looking forward to the new service version.

**Comment by leoninez** [comment]
Similar problem as :

`  java.lang.VerifyError: Bad type on operand stack
[info] Exception Details:
[info]   Location:
[info]     org/apache/hadoop/fs/azure/AzureNativeFileSystemStore.retrieveMetadata(Ljava/lang/String;)Lorg/apache/hadoop/fs/azure/FileMetadata; @227: invokestatic
[info]   Reason:
[info]     Type 'com/microsoft/azure/storage/blob/BlobListingDetails' (current frame, stack[3]) is not assignable to 'java/lang/Enum'
[info]   Current Frame:
[info]     bci: @227
[info]     flags: { }
[info]     locals: { 'org/apache/hadoop/fs/azure/AzureNativeFileSystemStore', 'java/lang/String', 'org/apache/hadoop/fs/azure/StorageInterface$CloudBlobWrapper' }
[info]     stack: { 'org/apache/hadoop/fs/azure/AzureNativeFileSystemStore', 'java/lang/String', integer, 'com/microsoft/azure/storage/blob/BlobListingDetails' }
[info]   Bytecode:
[info]     0x0000000: 012a b400 12a6 001d 12fa 04bd 000a 5903
[info]     0x0000010: 2ab4 0029 53b8 0053 4dbb 005c 592c b700
[info]     0x0000020: 5ebf b200 2f13 0151 2bb9 0032 0300 2ab2
[info]     0x0000030: 00ec b700 ffb2 00df a600 0501 b02b 1244
[info]     0x0000040: b600 5199 0013 bb01 5259 2b09 b801 24b2
[info]     0x0000050: 0153 b701 54b0 2a2b b701 014d 012c a500
[info]     0x0000060: 7f2c 2ab7 008e b901 5502 0099 0072 b200
[info]     0x0000070: 2f13 0156 2bb9 0032 0300 2c2a b700 8eb9
[info]     0x0000080: 0137 0200 2cb9 0157 0100 4e2c b801 5899
[info]     0x0000090: 0027 b200 2f13 0159 2bb9 0032 0300 bb01
[info]     0x00000a0: 5259 2b2d b601 5ab6 015b 2a2c b701 5cb2
[info]     0x00000b0: 015d b701 54b0 b200 2f13 015e 2bb9 0032
[info]     0x00000c0: 0300 bb01 5259 2b2a 2c2d b701 5f2d b601
[info]     0x00000d0: 5ab6 015b 2a2c b701 5cb7 0160 b02a 2b04
[info]     0x00000e0: b201 39b8 013a 012a b700 8eb7 0161 4e2d
[info]     0x00000f0: b901 6201 003a 0419 04b9 0041 0100 9900
[info]     0x0000100: 5b19 04b9 0042 0100 c001 633a 0519 05c1
[info]     0x0000110: 010a 9a00 0b19 05c1 0108 9900 3cb2 002f
[info]     0x0000120: 1301 6419 05b9 0165 0100 b900 3203 0019
[info]     0x0000130: 05c0 0166 4d2c b901 5701 003a 06bb 0152
[info]     0x0000140: 592b 1906 b601 5ab6 015b 2a2c b701 5cb2
[info]     0x0000150: 0153 b701 54b0 a7ff a101 b04d bb00 9059
[info]     0x0000160: 2cb7 00c2 bf                           
[info]   Exception Handler Table:
[info]     bci [46, 60] => handler: 347
[info]     bci [61, 85] => handler: 347
[info]     bci [86, 181] => handler: 347
[info]     bci [182, 220] => handler: 347
[info]     bci [221, 341] => handler: 347
[info]     bci [342, 346] => handler: 347
[info]   Stackmap Table:
[info]     same_frame(@34)
[info]     same_frame(@61)
[info]     same_frame(@86)
[info]     append_frame(@182,Object[#836],Object[#856])
[info]     chop_frame(@221,1)
[info]     append_frame(@247,Object[#857],Object[#649])
[info]     append_frame(@285,Object[#858])
[info]     chop_frame(@342,1)
[info]     chop_frame(@345,1)
[info]     full_frame(@347,{Object[#632],Object[#631]},{Object[#704]})
[info]   at org.apache.hadoop.fs.azure.NativeAzureFileSystem.createDefaultStore(NativeAzureFileSystem.java:1190)
[info]   at org.apache.hadoop.fs.azure.NativeAzureFileSystem.initialize(NativeAzureFileSystem.java:1161)
[info]   at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2812)
[info]   at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:386)
[info]   at com.microsoft.dataflow.transformers.FileReader$$anonfun$read$1.apply(FileStore.scala:154)
[info]   at com.microsoft.dataflow.transformers.FileReader$$anonfun$read$1.apply(FileStore.scala:154)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at com.microsoft.dataflow.transformers.FileReader.read(FileStore.scala:154)
[info]   at com.microsoft.dataflow.transformers.store.BlobReader.read(BlobStore.scala:72)
[info]   at com.microsoft.dataflow.transformers.SourcePlanner$.physicalPlanInternal(SourceV2.scala:304)`

I believe, the new azure-storage-blob 10.3 should append one version control in the package name such as : com.microsoft.azure.storage.v10.xxx

or need to fully check the class conflict.

**Comment by marcioos** [comment]
Hello,
Is there any estimate date for when the fix for this issue will be released? 
As of now, we can't use 10.5.0 alongside the latest EventHub EventProcessorHost library.

**Comment by jacobw125** [comment]
To help anyone else who's googling for this, I believe this is also affecting the azure-blob-storage library. I'm using SBT and saw that com.microsoft.azure / azure and com.microsoft.azure / azure-blob-storage led to a signing exception which is caused by this naming conflict.

**Comment by rickle-msft** [comment]
@marcioos. Sorry for not responding earlier. I never saw your comment for some reason. We are in the final stages of a release right now.

@jacobw125 where does the azure-blob-storage library live so I can take a look at it? Thanks for pointing this out.

**Comment by jacobw125** [comment]
@rickle-msft I was remembering the name wrong, I've updated my previous comment with more accurate and specific information.

**Comment by jacobw125** [comment]
Using the sbt-dependency-graph plugin, I was able to verify that com.microsoft.azure has a dependency on azure-storage:6.1.0, which is the v8 version of this library.

```
com.microsoft.azure:azure-storage:6.1.0 (this is the v8 library, causing conflicts)
  +-com.microsoft.azure:azure-mgmt-appservice:1.12.0
  | +-com.microsoft.azure:azure:1.12.0
  |     
  +-com.microsoft.azure:azure-mgmt-containerinstance:1.12.0
  | +-com.microsoft.azure:azure:1.12.0
  |     
  +-com.microsoft.azure:azure-mgmt-eventhub:1.12.0
  | +-com.microsoft.azure:azure:1.12.0
  |     
  +-com.microsoft.azure:azure-mgmt-sql:1.12.0
    +-com.microsoft.azure:azure:1.12.0
```

According to Maven central, this dependency on azure-storage:6.1.0 is present even in the most recent version of com.microsoft.azure:azure (1.20.1). 

This seems like a big problem - it's not just the upgrade story that's broken, if my understanding is correct, it's impossible to use these the v10 blob storage library and the azure management tools on the same classpath.

**Comment by rickle-msft** [comment]
Hi, @jacobw125 @marcioos @leoninez @carlosbarragan @rykawagu. v11.0.0 just went out on Friday afternoon. Could you please give that a try and validate whether or not the release resolves that issue. I believe we changed any type names that are in conflict with v8, but please let us know if you continue to experience issues. 

I will close this issue as I believe the latest release resolves the problem, but please feel free to reopen it if you continue to experience issues.

**Comment by jacobw125** [comment]
Thank you @rickle-msft , confirmed this fixed my issue!
