### ISSUE TITLE
MaxResults returned in list blobs response should be Integer instead of int

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#411]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.2.0

### What problem was encountered?
In my application, I make a call to list blobs with either null or a positive integer for MaxResults parameter and then get page size from `MaxResults` returned in the response (`ListBlobsHierarchySegmentResponse`) to make subsequent list calls if there is a next marker available. If the MaxResults value is set to null with the first request, then the response from the Azure Storage API doesn't contain MaxResults. During response deserialization, it gets converted to a zero since the type is `int`. My subsequent list call fails as I'm now passing 0 which is not a valid value. Here's a sample code snippet that demonstrates this:

```
Integer maxResults = null;
ListBlobsOptions options = new ListBlobsOptions().withMaxResults(maxResults);

ContainerListBlobFlatSegmentResponse response = containerURL.listBlobsFlatSegment(null, options)
                                                            .blockingGet();

maxResults = response.body().maxResults();

// Throws an IllegalArgumentException saying 'MaxResults must be greater than 0'
options = new ListBlobsOptions().withMaxResults(maxResults);

```

### Have you found a mitigation/solution?
Yes, I convert it to null if the MaxResults returned in the response is zero.

**Comment by rickle-msft** [comment]
Hey, @SukruthKS. Thanks for pointing this out. I double checked the docs and our specs, and it looks like you're right. MaxResults is listed as required on the response, which is why it's an `int`, when it's actually not guaranteed to be present, so it should be an `Integer`. I'll file this issue and it should be able to make it into our next breaking release

**Comment by rickle-msft** [comment]
This fix is included in the latest release. I will close this issue now as I believe it has been resolved, but please feel free to reopen it if you continue to experience problems.
