### ISSUE TITLE
Impact of CloudFile.create size mismatch with actual file size

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-storage-java#412]
### Which service(blob, file, queue, table) does this issue concern?
file

### Which version of the SDK was used?
6.1.0

### What problem was encountered?
CloudFile.create() must provide a size. If the actual file is smaller that this, I found spaces concatenated real content. It's hard to know actual size when creating file. What happens when actual size is larger or smaller?

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
Hi, @warrenzhu25. Thank you for posting your question. When you create the file, it does create an empty file of the specified size, so there are effectively zeros in any unused space. You should be able to write to the file, and if you need to trim it to be the actual size of valid content, you can make a list ranges call, get the last valid range, and resize the file based on the result of that check. In either case of the file size being different than what you originally allocated, you can change the size with a call to setProperties

**Comment by warrenzhu25** [comment]
Thanks for reply. Could you share a code sample about how to do this? What do you mean by `make a list ranges call`? Regarding `setProperties`, how should I know in advance how large is the file? And when initial size is smaller than actual, exception is thrown. How should I handle this?

**Comment by rickle-msft** [comment]
If you're actively editing the file and you don't know how much data you have upfront, you'll have to make a best guess and then resize as you go, similar to how an ArrayList grows. Start with something like 1MB, and if you get an exception saying you're out of space, make a setProperties call to grow the file (perhaps doubling the size?) and then continue writing. Repeat this process until you're finished growing the file, then you can trim off any extra space if you want to with the following.

```
ArrayList<FileRange> ranges = file.downloadFileRanges();
long endOfFile = ranges.get(ranges.size()-1).getEndOffset();
file.resize(endOfFile);
```

downloadFileRanges returns a list of "valid" ranges of the file, meaning ranges that have been written to, so getting the last one means you are getting the end of the file, then you just resize the file to be that size. Of course, if you keep track of the size when you're doing the writes (say by just storing what the largest offset is among all your writes), then you could avoid the network call for download ranges and just resize based on that.

**Comment by rickle-msft** [comment]
I am going to close this issue as it has been dormant for a while and the questions here seem to have been addressed without follow up. Please feel free to reopen the issue if there are further questions or concerns.
