### ISSUE TITLE
JsonMappingException when quotes are parsed in eTAG  

### ISSUE THREAD

**Issue by pamu** [Azure/azure-storage-java#419]
### Which service(blob, file, queue, table) does this issue concern?

- Azure Storage service (While experimenting with Azurite blob)

### Which version of the SDK was used?

- azure-storage-blob
- 10.3.0

### What problem was encountered?
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to decode VALUE_STRING as base64 (MIME-NO-LINEFEEDS): Illegal character '"' (code 0x22) in base64 content
[error]  at [Source: {"date":"Wed, 02 Jan 2019 16:56:59 GMT","content-length":"31","x-ms-version":"2016-05-31","Connection":"keep-alive","x-ms-blob-content-md5":"undefined","x-ms-request-server-encrypted":"false","x-ms-blob-type":"BlockBlob","last-modified":"Wed, 02 Jan 2019 10:58:32 GMT","content-range":"bytes 0-30/31","etag":"\"LjOfgK/d1rTN162pjZZKb9eXKQw\"","content-type":"text/csv; charset=utf-8","accept-ranges":"bytes","x-ms-request-id":"6b1b07b1-0eaf-11e9-ab63-cdb2bf176142","X-Powered-By":"Express"}; line: 1, column: 152]
```

### Have you found a mitigation/solution?

- Nope

**Comment by rickle-msft** [comment]
Hi, @pamu. Can you give me some more information about the request you were making? Which method were you calling with what parameters?

**Comment by pamu** [comment]
@rickle-msft 
Hi, Thanks for quick reply.

I am trying to test my demo app with azurite . Here is the azurite response
```
▶ az storage blob upload -c mappings -n store_mappings.csv -f user_mappings.csv --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;'
Finished[#############################################################]  100.0000%
{
  "etag": "\"snXFBAfcscEdTKjoHmpCiWKsKz8\"",
  "lastModified": "2019-01-02T21:49:21+00:00"
}
```

**Comment by pamu** [comment]
@rickle-msft Bug is at `com.microsoft.rest.v2.protocol.HttpResponseDecoder.decode(HttpResponseDecoder.java:68)`

**Comment by rickle-msft** [comment]
@pamu. Thank you for the stack trace. Can you also please tell me which service api you are calling? e.g. GetProperties, StageBlock, etc.?

By the way, I notice your account key is in the azurite command you shared. You may want to rotate that key.

**Comment by pamu** [comment]
@rickle-msft Here is the code . 
```
 val containerURL = serviceURL.createContainerURL(blob.containerName)
    val blobStream =
      Source
        .fromPublisher(
          containerURL
            .createBlockBlobURL(blob.blobName)
            .download()
            .toFlowable)
        .flatMapConcat { resp: DownloadResponse =>
          val bodyBytes: Flowable[ByteBuffer] = resp.body(new ReliableDownloadOptions())
          Source.fromPublisher(bodyBytes)
        }
        .map(ByteString(_))
```

**Comment by rickle-msft** [comment]
@pamu I just called these apis against the service, and the service also returns the etag with quotes for these operations. The difference is that the quotes aren't escaped ```ETag: "0x8D6710B134D7F07"```. I'm not sure off the top of my head why the deserializer wouldn't like having the quotes escaped, but I'm inclined to suggest filing this as a bug on [Azurite](github.com/Azure/Azurite) since what they return should match the service.

**Comment by rickle-msft** [comment]
I am going to close this issue as it seems to be unrelated to the Storage SDK, but please feel free to reopen it or post a new issue as appropriate.
