### ISSUE TITLE
Invalid value '' for EdmType

### ISSUE THREAD

**Issue by lhlyg** [Azure/azure-storage-java#42]
In a word, the parseJsonEntity() didn't process 'null' value of query results correctly. 
Here is the scenario: I'm querying a row with partitionkey 'keyX' and column 'fieldx', but actually, there doesn't exist the column 'fieldx' for the 'keyX' row. So the below codes 'var = parser.getValueAsString()' is assigning 'null' to val. 

Class: TableDeserializer
Method: parseJsonEntity
key = parser.getCurrentName();
parser.nextToken();
val = parser.getValueAsString();
edmType = evaluateEdmType(parser.getCurrentToken(), parser.getValueAsString());

Finally, the below exception is thrown.
Class: EntityProperty
Method: EntityProperty
else {
      // these are overwritten when this is called from the table parser with a more informative message
      if (edmType == null) {
                throw new IllegalArgumentException(SR.EDMTYPE_WAS_NULL);
       }
       throw new IllegalArgumentException(String.format(SR.INVALID_EDMTYPE_VALUE, edmType.toString()));//<-- this exception is thrown
}

**Comment by emgerner-msft** [comment]
Could you provide some code showing how you're using the storage library and hitting this issue? We can see you're probably using JsonNoMetadata but the exact API calls you're making to hit this would be most helpful in debugging the problem.

**Comment by lhlyg** [comment]
TableQuery<DynamicTableEntity> projectionQuery =
                TableQuery.from(DynamicTableEntity.class)
                        .where(TableQuery.generateFilterCondition("PartitionKey", TableQuery.QueryComparisons.EQUAL, key));
if(fields!=null)//fields is a Set<String> 
     projectionQuery = projectionQuery.select(fields.toArray(new String[fields.size()]));         
  
CloudTable tableX = azureTableDB.getTableReference(tableName);
Iterable<DynamicTableEntity> executionResult = tableX.execute(projectionQuery);
if(executionResult.iterator().hasNext())
{
         DynamicTableEntity entity = executionResult.iterator().next();
         result.putAll(extractAttributes(entity.getProperties()));
}

**Comment by emgerner-msft** [comment]
This looks like a bug. The query should return an EntityProperty object with a value of null and a type of string when the selected field does not exist. We'll fix this in our next release. Thanks for reporting this!

**Comment by emgerner-msft** [comment]
This has been fixed in our 2.2.0 release. Thanks!
