### ISSUE TITLE
File attribute fetch failed due to URI parsing error

### ISSUE THREAD

**Issue by saykumar** [Azure/azure-storage-java#424]
### Which service(blob, file, queue, table) does this issue concern?
File

### Which version of the SDK was used?
v8.0.0

### What problem was encountered?
When getting file attributes for a file with `[` or `]` in the name, we get a URI parse error. These files were copied over using the AzCopy command from Blob to File.

We suspect that the header `x-ms-copy-source` has something to do with this validation error.

```
Caused by: java.net.URISyntaxException: Illegal character in path at index 84: https://<REDACTED>.blob.core.windows.net/<REDACTED>/[sample]%20sample?sv=2017-07-29&sr=b&sig=<REDACTED>&sp=r&api-version=2017-07-29
   at java.net.URI$Parser.fail(URI.java:2848)
   at java.net.URI$Parser.checkChars(URI.java:3021)
   at java.net.URI$Parser.parseHierarchical(URI.java:3105)
   at java.net.URI$Parser.parse(URI.java:3053)
   at java.net.URI.<init>(URI.java:588)
   at com.microsoft.azure.storage.file.FileResponse.getCopyState(FileResponse.java:62)
   at com.microsoft.azure.storage.file.FileResponse.getFileAttributes(FileResponse.java:165)
   at com.microsoft.azure.storage.file.CloudFile$7.preProcessResponse(CloudFile.java:1554)
   at com.microsoft.azure.storage.file.CloudFile$7.preProcessResponse(CloudFile.java:1524)
   at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:148)
   ... 18 common frames omitted
```

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
Hi, @saykumar. Which version of azcopy are you using?

**Comment by saykumar** [comment]
@rickle-msft `azcopy 7.3.0-netcore` on Linux

**Comment by saykumar** [comment]
Any ideas on how we could get past this?

**Comment by rickle-msft** [comment]
Sorry, I forgot to follow up. I created an issue in our backlog, so our team will address this as soon as possible. It looks like the failure is coming from the java URI parser, and I think that is because according to the [RFC for URIs](https://tools.ietf.org/html/rfc2396#section-2.4.3), square brackets are excluded from URIs and, "Data corresponding to excluded characters must be escaped in order to be properly represented within a URI." I would recommend devising a naming scheme which only includes valid URI characters.

**Comment by saykumar** [comment]
Thanks @rickle-msft for the update. Unfortunately, these files belong to our users and we don't have the ability to rename them. We'll wait for the SDK update :+1:

**Comment by ksangareddi** [comment]
+1 for a quick resolution on this issue.

**Comment by rickle-msft** [comment]
Can you request that your customers provide names that are valid URIs? Or if you so desire, you could sanitize the file names and escape the invalid characters before trying to create the URI? I'm skeptical this is something we can really resolve for you as the exception comes from java's own URI parser, which is behaving reasonably according to the RFC

**Comment by rickle-msft** [comment]
@saykumar @ksangareddi. Is there any update on this issue? Please let us know if we can assist you further.

**Comment by sayash** [comment]
@rickle-msft We couldn't get it to work when we tried it last in January. Since then, we've removed that use-case and haven't tested it since.

**Comment by rickle-msft** [comment]
I see. Thank you for your response. I am sorry that we could not find a better solution for you.

I will close this issue now as I think the discussion has concluded, albeit unsatisfactorily, without any immediate action items to track, but please feel free reopen the issue or post again if you wish to continue the conversation.
