### ISSUE TITLE
How to find if a BlockBlobURL exists?

### ISSUE THREAD

**Issue by patrickmayer0** [Azure/azure-storage-java#425]
Hi,

When using a ContainerURL or BlockBlobURL, is there a method to find out if a BlockBlobURL actually exists in blob storage? Sorry for the naïve question but, aside from listing them with containerURL.listBlobsFlatSegment(marker, options) and filtering on the one to find, is there a better way to do this?

Using azure-storage-blob 10.4.0

I suppose I could also try to download the first byte off that BlockBlorURL with blockURL.download(range, accessConditions, rangeGetContentMD5, context) and let it fail if nothing'S found.

But there is surely a more elegant way of doing this.

Regards,
Patrick

**Comment by rickle-msft** [comment]
Hi, @patrickmayer0. Thank you for your question. The typical pattern for checking existence of a resources is by doing a getProperties call and interpreting a 404 as non-existent. There's actually not a service call exclusively for this purpose, and even in the legacy SDK, the exists() method was implemented as a getPropeties call under the hoods.

**Comment by patrickmayer0** [comment]
Thanks for your quick reply. getProperties is certainly lighter than getting the first byte off a non-existent resource. I'll use that.
Regards,
Patrick
