### ISSUE TITLE
How can I suspend channel.read() when out-channel is not writable as Proxy

### ISSUE THREAD

**Issue by Zeymo** [Azure/azure-storage-java#427]
As a proxy server under v10, we receive download command and get block from azure (in-channel) and write body-bytes to client (out-channel).  From SDK , response just a **Single<HttpResponse>**  don't have backpressure feature，How can I suspend channel.read() when out-channel is not writable?

**Comment by rickle-msft** [comment]
Hi, @Zeymo. Thank you for your question. The download response you get is a Single. The body which is the actual content is a Flowable. You should be able to add a backpressure strategy to the Flowable representing the download stream. If you need to add backpressure to the whole download response, you can convert the Single to a Flowable with the toFlowable() operator. Does that help?
