### ISSUE TITLE
Need readTimeout for stream body download

### ISSUE THREAD

**Issue by Zeymo** [Azure/azure-storage-java#428]
Now SDK v10 only have **request-timeout** for Restful server, but for stream/flowable content **read-timeout** maybe more exactly and fit demand

**Comment by rickle-msft** [comment]
Flowable, the type of the response body, has a variety of built in timeout operators (such as [this one](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Flowable.html#timeout-long-java.util.concurrent.TimeUnit-)). Do any of those fit your scenario?

**Comment by Zeymo** [comment]
@rickle-msft  In procudction, we actually split timeout to **connention-timeout**,**acquire-connection-timeout** and **read-timeout**, but build in timeout operators just include they all.
IMO, for stream body read-timeout  just the timeout of emitter body content

**Comment by rickle-msft** [comment]
I'm not sure exactly what the distinction between connection-timeout and acquire-connection-timeout are, but essentially you can apply the timeout operator to different parts of your work flow. To set a timeout for getting the HTTP response back, set a timeout on the Single<DownloadResponse>. To set a read-timeout on the body to limit how much time you spend waiting for data, set a timeout on the Flowable<ByteBuffer> that is the body. To set a timeout on how long it takes to read the whole body, you can transform the body to a Completable that will notify you when it is finished, and you can set a timeout on the completion event.

**Comment by Zeymo** [comment]
I will try it ,thank u
