### ISSUE TITLE
Getting a java.lang.SecurityException when using package azure-storage v8.0.0 and azure-storage-blob v10.4.0

### ISSUE THREAD

**Issue by patrickmayer0** [Azure/azure-storage-java#430]
Hi,
We're using both azure-storage v8.0.0 and azure-storage-blob v10.4.0 in the same project. Basically, we parse our connectionString with the com.microsoft.azure.storage.StorageCredentialsAccountAndKey.tryParseCredentials(...) provided by azure-storage v8.0.0, then use the  azure-storage-blob v10.4.0 HttpPipeline to do the work.

```
import java.net.URL;
import java.util.Locale;

import com.microsoft.azure.storage.StorageCredentialsAccountAndKey;
import com.microsoft.azure.storage.blob.ContainerURL;
import com.microsoft.azure.storage.blob.PipelineOptions;
import com.microsoft.azure.storage.blob.ServiceURL;
import com.microsoft.azure.storage.blob.SharedKeyCredentials;
import com.microsoft.azure.storage.blob.StorageURL;
import com.microsoft.rest.v2.http.HttpPipeline;

import lombok.SneakyThrows;

public class Test { 
@SneakyThrows
    public static void main(String[] args) {
        StorageCredentialsAccountAndKey creds = (StorageCredentialsAccountAndKey) StorageCredentialsAccountAndKey
                .tryParseCredentials(
                        "DefaultEndpointsProtocol=...;EndpointSuffix=core.windows.net");
        String accountName = creds.getAccountName();
        String accountKey = creds.exportBase64EncodedKey();
        SharedKeyCredentials credential = new SharedKeyCredentials(accountName, accountKey);
        HttpPipeline pipeline = StorageURL.createPipeline(credential, new PipelineOptions());
        URL u = new URL(String.format(Locale.ROOT, "https://%s.blob.core.windows.net", accountName));
        ServiceURL serviceURL = new ServiceURL(u, pipeline);
        ContainerURL containerURL = serviceURL.createContainerURL("store");

    }
```

But ... we're getting this exception as it seems the StorageCredentialsAccountAndKey provided by azure-storage v8.0.0 is in a package that's also provided by azure-storage-blob v10.4.0... And both jar files signatures are different:

```
Exception in thread "main" java.lang.SecurityException: class "com.microsoft.azure.storage.GeneratedStorageClient"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1143)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:898)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at com.microsoft.azure.storage.blob.StorageURL.<init>(StorageURL.java:45)
	at com.microsoft.azure.storage.blob.ServiceURL.<init>(ServiceURL.java:51)
	at Test.main(Test.java:86)
```

Exception is thrown by this line:
`ServiceURL serviceURL = new ServiceURL(u, pipeline);`
Please advise on how to work around this problem.
Best regards,
Patrick

**Comment by patrickmayer0** [comment]
For the sake of completeness, here's and excerpt of our pom.xml file ...

```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>8.0.0</version>
        </dependency>
        
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
			<version>10.4.0</version>
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-servicebus</artifactId>
			<version>1.2.10</version>
		</dependency>
```

**Comment by patrickmayer0** [comment]
Right now, the work around we've found is exclude azure-storage v8.0.0 and parse the connectionString manually... Not very adequate but works correctly, apparently ...

**Comment by rickle-msft** [comment]
Hi, @patrickmayer0. Thank you for reporting this and apologies for the inconvenience. We typically don't advocate for the use of connection strings any more, so if you would be willing to use an alternate means of getting your connection info, I'd be happy to help with that.

If you are bound to using connection strings, can you help provide a little more info, please:

- Can you try the same code with v8 and v10.3.0 and again with v7 and v10.4.0?
- Do you get the same issue if you try to use a different type in the com.microsoft.azure.storage package from the v8 library? For instance, AccessCondition?
- Do you get the same issue if you try to use a type from the com.microsoft.azure.storage.blob package in both libraries? Say CloudBlockBlob and BlobURL?

**Comment by patrickmayer0** [comment]
Hi,

> Can you try the same code with v8 and v10.3.0 and again with v7 and v10.4.0?
Given the deadlines we have, not really.

> Do you get the same issue if you try to use a different type in the com.microsoft.azure.storage package from the v8 library? For instance, AccessCondition?
Given the actual stack trace: "Exception in thread "main" java.lang.SecurityException: class "com.microsoft.azure.storage.GeneratedStorageClient"'s signer information does not match signer information of other classes in the same package", I doubt it is worth checking this.

> Do you get the same issue if you try to use a type from the com.microsoft.azure.storage.blob package in both libraries? Say CloudBlockBlob and BlobURL?
Well, we're using ContainerURL and this is where it fails. So, I can only guess we'd get the same issue.

You mention alternatives to connectString: would you kindly explain what you have in mind? If the newer method is "the way to the future", it would be worth implementing it in our environment.

Best regards,
Patrick

**Comment by rickle-msft** [comment]
Typically just using the account url and key themselves are recommended right now; it was an intentional decision in the new version to leave out connection string support. This is in anticipation of some other changes that will be coming that I don't think I can disclose here yet, but suffice it to say that change in some ways precludes the use of connection strings. 

Actually, even more preferable is using OAuth token credentials to authenticate with your identity. If you would be able, we strongly recommend switching to token credentials because they are faster and seen as more secure because of the way they can be used to more granularly manage permissions.

**Comment by patrickmayer0** [comment]
Thanks for your answer.
Regards,
Patrick
