### ISSUE TITLE
SDK v10 logging SAS token

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#431]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
10.4.0

### What problem was encountered?
The SDK logs SAS token added to the request URL. It'd be great if the sensitive part of the SAS token (sig) can be scrubbed before logging. Also, it'd be useful to log Client Request ID for debugging.

### Have you found a mitigation/solution?
No. The only way I found was to turn off logging altogether.

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thank you for logging this issue and apologies for the inconvenience. What version of the SDK are you using? The code checked into master has this here, which should be redacting the signature value on the SAS token https://github.com/Azure/azure-storage-java/blob/master/src/main/java/com/microsoft/azure/storage/blob/LoggingFactory.java#L294

**Comment by SukruthKS** [comment]
Hi @rickle-msft, thanks for the prompt response! I'm using version 10.4.0 of the SDK. In the LoggerFactory class, for example, it's not redacting the signature in the line 162 before sending the request.

```
if (this.shouldLog(HttpPipelineLogLevel.INFO)) {
    String logMessage = String.format("'%s'==> OUTGOING REQUEST (Try number='%d')%n", request.url(),
        this.tryCount);
    this.log(HttpPipelineLogLevel.INFO, logMessage);
 }
```

**Comment by rickle-msft** [comment]
I see. Not scrubbing the outgoing url is definitely an oversight, and we will definitely fix it. Thank you for catching that

**Comment by rickle-msft** [comment]
A fix for this has been merged into dev and will be included in the next release. I will leave this open until that time, but the actual code for this is complete.

**Comment by SukruthKS** [comment]
Thanks @rickle-msft !

**Comment by rickle-msft** [comment]
v11.0.0 has been released which contains this fix. I will close this issue now as I believe it has been resolved, but please feel free to reopen it if you continue to experience problems.
