### ISSUE TITLE
CloudStorageAccount.parse doesn't throw an exception when passing in an empty key.

### ISSUE THREAD

**Issue by dbousamra** [Azure/azure-storage-java#44]
`CloudStorageAccount.parse(DefaultEndpointsProtocol=http;AccountName=cammystaging;AccountKey=)` will happily return a `CloudStorageAccount.`

It should throw an exception.

**Comment by emgerner-msft** [comment]
While the current code will throw an exception if you try to use the said account to make a storage request, we agree it's more intuitive for it to fail earlier. We will make this change in an upcoming release. Thank you for the suggestion!

**Comment by emgerner-msft** [comment]
This should be addressed as of the most recent release (3.0).

**Comment by dbousamra** [comment]
Great to hear :D
