### ISSUE TITLE
Connecting to HTTP proxy for HTTPS endpoints

### ISSUE THREAD

**Issue by lnr0626** [Azure/azure-storage-java#445]
### Which service(blob, file, queue, table) does this issue concern?
I'm using blob, however I assume that it will affect all of them

### Which version of the SDK was used?
10.5.0

### What problem was encountered?
I need to connect to azure storage through an http proxy (not https); however when the sdk attempts to make the connection it uses https. There doesn't appear to be a way to override this setting either. I'm setting up the pipeline with an http client created like so:
```
HttpClient.createDefault(new HttpClientConfiguration(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort))))
```

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
Hi, @lnr0626. Thanks for posting this. You want the connection between your machine and your proxy to be http. Do you want your connection between the proxy and storage to be over https or http?

**Comment by lnr0626** [comment]
I want the connection between the proxy and storage to be over https

**Comment by lnr0626** [comment]
It looked like the issue might stem from [this line](https://github.com/Azure/autorest-clientruntime-for-java/blob/v2/client-runtime/src/main/java/com/microsoft/rest/v2/http/SharedChannelPool.java#L257):

```
            if (proxy == null) {
                channelRequest.channelURI = channelRequest.destinationURI;
            } else {
                InetSocketAddress address = (InetSocketAddress) proxy.address();
                channelRequest.channelURI = new URI(String.format("%s://%s:%d", uri.getScheme(), address.getHostString(), address.getPort()));
            }
```

where the channel assumes that the connection to the proxy should be using the same scheme as the URI

**Comment by jianghaolu** [comment]
The fix is released in  https://search.maven.org/artifact/com.microsoft.rest.v2/client-runtime/2.0.3/jar. Please verify.

**Comment by rickle-msft** [comment]
I will close this issue now as it seems to have been resolved with no follow up. Please feel free to reopen it if you continue to experience issues.
