### ISSUE TITLE
Running code sample warns of illegal restricted access operation

### ISSUE THREAD

**Issue by mattvryan** [Azure/azure-storage-java#447]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.5.0

### What problem was encountered?
I tried a very simple example based as closely as I could on the [code sample in the README.md](https://github.com/Azure/azure-storage-java/blob/master/README.md#code-sample).  When I run my code, it creates the container, uploads the blob, verifies it, and then deletes the blob and container as expected.  But warning messages are printed to the console about an illegal restricted access operation in the SDK code:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.microsoft.rest.v2.Validator to field java.util.HashMap.serialVersionUID
> WARNING: Please consider reporting this to the maintainers of com.microsoft.rest.v2.Validator
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

I'm reluctant to rely on this SDK in production with this warning present; are there plans to address this?

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
Hi, @mattvryan. I am sorry that you are hitting this issue. Can I ask you to please post the issue on [this repo](https://github.com/azure/autorest-clientruntime-for-java) as they own the rest.v2 package

**Comment by mattvryan** [comment]
I posted the issue to the AutoRest Client Runtimes for Java project via [this issue](https://github.com/Azure/autorest-clientruntime-for-java/issues/569), as requested.
