### ISSUE TITLE
BlockBlobURL.download().blockingGet() on an empty file throws an exception (HTTP 416 error)

### ISSUE THREAD

**Issue by maximestlaurent** [Azure/azure-storage-java#450]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.5

### What problem was encountered?
When using BlockBlobURL.download().blockingGet() to download an empty file, a StorageException containing an HTTP 416 error is thrown.

```
// This throws a StorageException when blobUrl designates an empty file.
DownloadResponse downloadResponse = blobUrl.download().blockingGet();
```

### Have you found a mitigation/solution?
Catching the exception and returning an empty response, however I'm uncertain if that error can be thrown in different scenarios.

**Comment by rickle-msft** [comment]
Hi, @maximestlaurent. Thank you for reporting this issue. It does seem to be the case that the service does not like the whole-range format ("0-") for empty blobs, which is what we default to when a range is not passed. This should be a pretty quick fix that we can get in for the release we're planning next week

**Comment by maximestlaurent** [comment]
This would be version 10.6?

**Comment by rickle-msft** [comment]
It will probably go out with some breaking changes, so it will be v11.0

**Comment by rickle-msft** [comment]
@maximestlaurent v11.0.0 has been released and should address this issue. I will close this issue as I believe as it has been resolved, but please feel free to reopen it if you continue to experience issues.

**Comment by maximestlaurent** [comment]
Thanks for the heads up! I will migrate to SDK 11 and get back to you if the issue persists.
