### ISSUE TITLE
Support for Immutable blob storage policy creation

### ISSUE THREAD

**Issue by abelsromero** [Azure/azure-storage-java#451]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.5.0
Windows 10, OpenJDK 11.0.2

### What problem was encountered?
There's no support to create an immutable blob storage policy.
See https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage.
There's no option in the API to create them. Also, I can access a container with both access and blob policies, but when using the methods "getAccessPolicy" only the first on is returned.

### Have you found a mitigation/solution?
I'll try directly using the REST API.

**Comment by rickle-msft** [comment]
Hi, @abelsromero. I apologize for the long delay in addressing this issue. Setting immutability policies is actually not supported in the data plane apis, but it is possible for you to set them in the [resource management apis](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/resource-manager/v2018_11_01/src/main/java/com/microsoft/azure/management/storage/v2018_11_01/ImmutabilityPolicy.java). 

Can you please describe in more detail the issue you are seeing related to the getAccessPolicy api? I don't quite understand the scenario you are describing.

**Comment by abelsromero** [comment]
> Can you please describe in more detail the issue you are seeing related to the getAccessPolicy api? I don't quite understand the scenario you are describing.

At the end, thanks to official support I found out about the resource management api and could solve creation + setting + lock of an immutable policy. The issue was more me, not understanding that the blob API did not provide this features and thinking that since access policies and immutable policies are under the "access polices" in the azure portal, both policies should be returned by the API in this repo.
Tbh, I still think the APIs are pretty confusing and resource management docs are not easy to find, but I guess this issue can be closed.
