### ISSUE TITLE
Update the version of jackson-databind off 2.8.11

### ISSUE THREAD

**Issue by NikolayMetchev** [Azure/azure-storage-java#454]
It seems azure-storage-blob still depends on jackson-databind 2.8.11. This is via com.microsoft.rest.v2:client-runtime:2.0.2.
That version of jackson-databind has a security vulnerability:
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72450

**Comment by rickle-msft** [comment]
Hi, @NikolayMetchev. Thank you very much for reporting this. I am investigating this now and will post updates here when I have new information.

**Comment by rickle-msft** [comment]
This has been resolved in the latest release. We upgraded our dependency to 2.1.1 of the runtime, which upgraded their dependency on Jackson.
