### ISSUE TITLE
Downloading empty blobs result in invalid 'blobRangeOffset' parameter in v8.2.0

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#460]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
8.2.0

### What problem was encountered?
When downloading empty blobs, it throws an exception saying `The value of the parameter 'blobRangeOffset' should be between 0 and -1`. It appears that this issue has been fixed in v11 based on the changelog `Fixed a bug that would set an invalid range header when downloading an empty blob.` but not in v8.2.0.

### Have you found a mitigation/solution?
Revert back to a lower version of the v8 SDK.

**Comment by rickle-msft** [comment]
Thanks for reporting this, @SukruthKS. Do you have a line number I can check for this specific case? I don't think we made any changes to errors around that in v8.2.0, so I'm surprised that downgrading has resolved this for you.

**Comment by SukruthKS** [comment]
I'm seeing this error at line 193 in [BlobInputStream](https://github.com/Azure/azure-storage-java/blob/v8.2.0/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/BlobInputStream.java) class. It checks that `blobRangeOffset` value is between 0 and (length of blob - 1) and if blob length is 0, it checks to make sure that the value is between 0 and -1 and raises this error.
I had reverted back to v8.0.0 as a workaround and looks like the feature to specify range and offset was introduced in v8.1.0.

**Comment by rickle-msft** [comment]
Ah. Thank you for pointing that out! Looks like my memory failed me! 

Are you blocked by having to use v8.0.0? I remember there originally being a signing issue using v8 and v11 together, but it sounds like maybe you guys worked around that?

**Comment by SukruthKS** [comment]
Yeah, we are not blocked by this. I tried v8.2.0 as per Peter's suggestion and found this issue. But I realized I need to build the package myself to shade a few dependencies so I cannot use the signed version anyways. So we will just stay on v8.0.0.

**Comment by rickle-msft** [comment]
Ok great. I'm glad you are not blocked. In that case, we will make this fix as a part of a small release we have planned for early next week. Please let us know if you need anything else

**Comment by rickle-msft** [comment]
This is being released right now, so I will close this issue. Please continue to post as you encounter issues or have questions.
