### ISSUE TITLE
SDK x-ms-version does not work with Premium Block Blob Storage

### ISSUE THREAD

**Issue by pwoody** [Azure/azure-storage-java#463]
### Which service(blob, file, queue, table) does this issue concern?
Premium Block Blob Storage

### Which version of the SDK was used?
8.2.0, but I was originally having the issue on 11.0.0 and I assume it still is a problem.

### What problem was encountered?
Any requests against Premium Block Blob Storage by default get an error when requesting through the SDK. It claims the following:
`com.microsoft.azure.storage.StorageException: The value for one of the HTTP headers is not in the correct format.`
It appears the latest x-ms-version "2018-11-09" does not work with Premium Block Blob Storage, downgrading to "2018-03-28" worked fine.

### Have you found a mitigation/solution?
Yes, manually adding the user header of ("x-ms-version", "2018-03-28") to the OperationContext will overwrite the bad version of "2018-11-09" and cause the request to succeed.

**Comment by chchgb** [comment]
I also met the same issue. with sdk version 11, I need to manually change the x-ms-version in Constants class. https://github.com/Azure/azure-storage-java/blob/master/src/main/java/com/microsoft/azure/storage/blob/Constants.java

**Comment by rickle-msft** [comment]
@pwoody @chchgb Sorry for the delay. We discussed this last week on our team and forgot to follow up. We think it's actually a configuration issue not related to this SDK. We'll look at the relevant switches over here and get back to you soon. Thank you for your patience.

**Comment by rickle-msft** [comment]
Can you guys double check using premium block blobs with the November service version and see if you are able to successfully make some requests?

**Comment by pwoody** [comment]
I still can't, but let me know if there is a specific set of requests you'd like me to try. Here is my repro in Java
```
    CloudStorageAccount parse = CloudStorageAccount.parse("CONNECTION_STRING");
    CloudBlobClient cloudBlobClient = parse.createCloudBlobClient();
    CloudBlobContainer test = cloudBlobClient.getContainerReference("test");
    test.createIfNotExists();
```
working:
```
    CloudStorageAccount parse = CloudStorageAccount.parse("CONNECTION_STRING");
    CloudBlobClient cloudBlobClient = parse.createCloudBlobClient();
    CloudBlobContainer test = cloudBlobClient.getContainerReference("test");
    OperationContext operationContext = new OperationContext();
    HashMap<String, String> headers = Maps.newHashMap();
    headers.put(Constants.HeaderConstants.STORAGE_VERSION_HEADER, "2018-03-28");
    operationContext.setUserHeaders(headers);
    test.createIfNotExists(null, null, operationContext);
```
Calling the REST API directly with this x-ms-version also fails, so it doesn't seem like this is exclusive to the java SDK. I'm just not sure of the best place to file this.

**Comment by pwoody** [comment]
Actually looks like this has been resolved server-side for premium blob storage now https://social.technet.microsoft.com/Forums/en-US/ae5a7703-136d-4928-8d59-448b40915a4a/premium-block-blob-storage-and-microsoftazurestorageblob-1001?forum=windowsazuredata

I think we can close this out?

**Comment by rickle-msft** [comment]
I believe you are correct. I think I jumped the gun a little bit when I responded as the work was in progress but had not quite completed yet.  I will close this issue now, but please feel free to reopen it or post again with any further concerns.

**Comment by wangyingmm** [comment]
is this fixed? I get the same exception recently

**Comment by rickle-msft** [comment]
@wangyingmm This was fixed on the service. Was this working previously and has recently started throwing the errors discussed above without a change to the client?

**Comment by wangyingmm** [comment]
> @wangyingmm This was fixed on the service. Was this working previously and has recently started throwing the errors discussed above without a change to the client?

@rickle-msft it was not working at very first beginning. but today I tried with Microsoft.Azure.Storage.Blob 10.0.3 it's working now. previously it was 11.1. is this related to service version. is that the client side must use same version as service side?

**Comment by rickle-msft** [comment]
What happened last time was there was a config file on the service that did not turn a feature on correctly, so it was completely independent of the client. I didn't discuss with the service team about this most recent case, but since it seems to have followed a similar pattern, I suspect it was a similar cause. 

Happy to hear it's working now.
