### ISSUE TITLE
Issues while trying out special endpoints other than the public storage endpoint

### ISSUE THREAD

**Issue by srinidhikarthikbs** [Azure/azure-storage-java#464]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
11.0.0

### What problem was encountered?
I'm not trying to do anything special here. I came across one of this special endpoint and was trying to see if it throws a specific error to catch in my application. 
**Two observations:**
1. Why does the SDK wait for a bit to throw TimeoutException when the number of tries is 1? Soon after throwing NullPointerException it should look at the number of retries which is 1 and throw a TimeoutException immediately right? Why does it wait? It gives me a feeling as if its gonna retry again, only to not retry in the end.
2. Why is it throwing a NullPointerException in the first place? If a storage account cannot be found or the endpoint is not recognized then I think it should be an appropriate error. 

**NullPointerException:**
`
Apr 23, 2019 2:06:53 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete()
java.lang.NullPointerException
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.emitError(NettyClient.java:426)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete(NettyClient.java:247)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**TimeoutException:**
`
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91)
	at io.reactivex.Single.blockingGet(Single.java:2656)
	at Test.main(Test.java:96)
Caused by: java.util.concurrent.TimeoutException
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.run(SingleTimeout.java:115)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Code:**
`
private static ServiceURL getClientReference(URL serviceURL,
		ICredentials azCreds)
	{
		// REST requests sent by the SDK can be configured using PipelineOptions
		// like retry policies, headers, logging etc.,
		HttpPipeline httpPipeline = StorageURL.createPipeline(
			azCreds,
			new PipelineOptions()
				.withClient(HttpClient.createDefault())
				.withRequestRetryOptions(new RequestRetryOptions(
					RetryPolicyType.EXPONENTIAL,
					4,
					60,
					4 * 1000L,
					120 * 1000L,
					null)));

		return new ServiceURL(serviceURL, httpPipeline);
	}

	public static void main (String[] args) throws IOException {

                String containerName = "endpointTesting";
		String prefix = "";
		Integer maxResults = null;

		BlobListDetails blobListDetails = new BlobListDetails().withMetadata(true);

		ListBlobsOptions listBlobsOptions = new ListBlobsOptions()
			.withMaxResults(maxResults)
			.withPrefix(prefix)
			.withDetails(blobListDetails);

		String newClientURL = "https://storageAccount.blob.core.cloudapi.de";

		ServiceURL client = getClientReference(new URL(newClientURL), new AnonymousCredentials());

		ContainerURL container = client.createContainerURL(containerName);

		ContainerListBlobFlatSegmentResponse response =
			container.listBlobsFlatSegment(null, listBlobsOptions)
				.blockingGet();

		BlobFlatListSegment listSegment = response.body().segment();
		List<BlobItem> blobs = listSegment == null
			? new ArrayList<>()
			: listSegment.blobItems();

		blobs.forEach(blob -> System.out.println(blob.name()));
	}
`

I am pretty sure its supposed to be handled gracefully than this.

### Have you found a mitigation/solution?
Nope.

**Comment by rickle-msft** [comment]
@srinidhikarthikbs Thank you for your questions/reporting this issue. 

For the NPE, this looks to be the same issue as #440. This has been resolved in our underlying dependency, and we are planning a bug fix release for today or tomorrow to upgrade to the version with that fix. 

For the timeout, I'm not exactly clear on what the behavior that you're seeing is. It would make sense to me if you're seeing a delay before the exception because of our retry timeout and the DNS taking a little while to fail to resolve, but I'm not sure what sort of delay you are experiencing after the NPE is being thrown. In any case, I think it will be best if we defer this part of the conversation until after you can try the fix mentioned above.

**Comment by srinidhikarthikbs** [comment]
Thanks @rickle-msft for the quick response. 
Yes, I believe I am seeing the delay before the exception because of retry timeout, but I'm talking about the TimeoutException. After the last retry it throws an NPE and goes into a delay and then throws TimeoutException. This delay doesn't really seem necessary, does it?

**Comment by rickle-msft** [comment]
I agree. Getting two exceptions for one error doesn't seem necessary to me. I don't quite see how that's possible, though. The retry policy and any related timeout operations should be ignored once you get the NPE. Are you sure the NPE and TimeoutException are coming from the same operation? I apologize if I am not understanding you correctly.

**Comment by srinidhikarthikbs** [comment]
I think I should have explained it better. At the end of each retry, the NPE is not exactly thrown, but definitely, prints in my running console like 
`WARNING: An exception was thrown by com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete()
java.lang.NullPointerException`

Only one exception is thrown ultimately (Timeout exception)

Let's say I make the call with 2 retires:
Order:

Try 1
Print NPE
Retry delay
Try 2
Print NPE
Retry delay - **Why this delay before throwing TimeoutException? **
TimeoutException

I should have used better language earlier. I hope its clear now.

**Comment by rickle-msft** [comment]
I see. Thank you for clarifying. I've seen bugs under other circumstances (now resolved) in which certain exceptions related to channel management would cause hangs in the application because the channels were dying but exceptions weren't getting propogated up to the application. In the end, the channel pool was drained and the application would hang. I am guessing this is something similar where the NPE is being thrown on a threadpool thread or something and therefore not being bubbled up to the application/retry policy. Instead, the retry policy just never sees a response and times out. 

In any case, I think the fix that is coming soon should address that as well. You can actually pull in this fix early if you would like to check by explicitly depending on v2.1.1 of the autorest-clientruntime (this will overwrite the storage sdk's dependency, which is all that is coming in the new update anyway. Put the following in your pom: 

```
<dependency>
            <groupId>com.microsoft.rest.v2</groupId>
            <artifactId>client-runtime</artifactId>
            <version>2.1.0</version>
</dependency>
```

**Comment by srinidhikarthikbs** [comment]
This is great, Thank you!
Now I see an UnknownHostException at the first try attempt.

**Comment by rickle-msft** [comment]
Awesome! I am going to close this issue as it seems your concerns have been addressed and we are able to adequately track this work through #440, but please feel free to post again if you have any further concerns.
