### ISSUE TITLE
Provide capability to control SLF4J logging

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#467]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
v11.0.0

### What problem was encountered?
In my application, slf4j logging is enabled to log at debug level so the storage SDK logs information about each request. This is great for production, but it is too verbose when running the application locally. One way to disable it is to add a filter in slf4j logger configuration, but it would require having separate configurations for different environments. This is not an ideal solution. It would be great if the SDK can expose a way to control its logging to slf4j. I understand that the SDK supports logging through other means like HttpPipelineLogger and Java core logger. Perhaps it will be simpler if there's just one way to configure all the logging. HttpPipelineLogger could be one choice, where a user can configure the log level and provide appropriate loggers to use.

### Have you found a mitigation/solution?
Please see the above section.

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thank you for the feedback. To clarify my understanding, are you asking for a way to programmatically configure SLF4J?

**Comment by SukruthKS** [comment]
I'm looking for a way to configure programmatically what the SDK logs to SLF4J. Basically, I want to be able to configure what the SDK logs independently of SLF4J configuration. Otherwise, my application and SDK logging are tied together and I need to either modify SLF4J config which affects the entire application or add a filter to remove all SDK logs.

**Comment by rickle-msft** [comment]
Thank you for those details. Is this blocking you guys at all? I'll add this item to be triaged and we'll work on getting this out soon.

**Comment by SukruthKS** [comment]
Thanks @rickle-msft ! It's more of a convenience thing than a blocker.

**Comment by SukruthKS** [comment]
@rickle-msft it'd be great if this can be treated with higher priority. I'm getting more and more complaints from other developers that there are way too many logs from the SDK and it's getting harder for them to search for other logs. 
The main thing I need is to be able to specify programmatically to the SDK the minimum level of logging to all channels like slf4j, java core logger etc.

**Comment by rickle-msft** [comment]
@SukruthKS thank you for keeping us updated on the status here. I believe we can start working on this next sprint (starts Monday)

To clarify, when you say java core logger, do you mean the HttpPipelineLogger? And are you ok with what is logged at each level and just want more control over setting the level? Or do you also have an issue with what is printed at each level?

**Comment by SukruthKS** [comment]
Great! Thanks for prioritizing this.

Sorry I meant to say `java.util.logging` when I said java core logger. But looks like it is used only for default logging which logs warnings and errors to a file in temp directory.

I think whatever is logged currently at each level is fine and just need control over setting the level.

**Comment by SukruthKS** [comment]
One minor improvement (unrelated to this) that can greatly help is if there is a way to correlate 'outgoing request' and request error. Logging factory logs a message like 'Unexpected failure attempting to make request' but there is no way to match it with the corresponding request. Thread Id won't work as there are way too many requests happening concurrently. Let me know if you want me to file this a separate issue.

**Comment by rickle-msft** [comment]
That's a good point as we have had difficulty with this on our end as well. I'll add it to the item description.

**Comment by rickle-msft** [comment]
I am going to close this issue as we have GAed v12 and are not intending to have any more feature releases for v11. The logging has been reworked in v12, but if you feel it still does not meet your needs, please feel free to post an issue on that repo.
