### ISSUE TITLE
RBAC authentication

### ISSUE THREAD

**Issue by marcioos** [Azure/azure-storage-java#468]
### Which service(blob, file, queue, table) does this issue concern?
Blob Storage

### Which version of the SDK was used?
8.3.0

### What problem was encountered?
I'm getting 403 responses from my Blob Storage accounts when using RBAC authentication (I'm trying to replace our current access key authentication method). Here's how I set it up, please tell me what I'm missing or doing wrong:

- On AAD, I registered an App which I'm using as a Service Principal for programmatically accessing Key Vaults (that works). Now I also want to use this same Service Principal for accessing my Blob Storage accounts.
- In the Azure portal, I assigned the _Contributor_ role to that Service Principal, on the resource group where my Blob Storage accounts belong to.
- I can verify in the Blob Storage account blade that the Service Principal has the _Contributor_ role on it (inherited from resource group).
- In the application code, I'm doing the following:
```java
// Acquire token
ApplicationTokenCredentials tokenCredentials = new ApplicationTokenCredentials(applicationId, tenantId, servicePrincipalPassword, AzureEnvironment.AZURE);
String accessToken = tokenCredentials.getToken("https://storage.azure.com/");
StorageCredentialsToken storageCredentialsToken = new StorageCredentialsToken(storageAccountName, accessToken);

// Create CloudBlobClient
CloudStorageAccount storageAccount = new CloudStorageAccount(storageCredentialsToken, true, "core.windows.net", storageAccountName);
CloudBlobClient cloudBlobClient = storageAccount.createCloudBlobClient();

// Get blob reference
CloudBlobContainer container = cloudBlobClient.getContainerReference(containerName);
CloudBlockBlob blob = container.getBlockBlobReference(blobName);

// Test request
blob.exists();
```
To which I get the exception: 
```
Caused by: com.microsoft.azure.storage.StorageException: This request is not authorized to perform this operation using this permission.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:2005)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1992)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1967)
	... 49 more
```

It seems that the authentication works, but the authorization fails. Besides the _Contributor_ role, I also tried assigning Storage specific roles, like _Storage Blob Data Contributor_. I also tried configuring the role assignment directly on the Storage account _and_ on the Blob container, without success.

### Have you found a mitigation/solution?
Not yet.

**Comment by rickle-msft** [comment]
@marcioos Are you seeing the same error even when you make the application a Storage Blob Data Contributor?

**Comment by marcioos** [comment]
Hi @rickle-msft, thanks for replying. Yes, I've tried that as well.

**Comment by rickle-msft** [comment]
Sorry I was unclear. I did notice that you have tried setting the Storage Blob Data Contributor role. I was hoping to confirm that the error you see when applying that role is in fact the same authorization error or if that gives you a different kind of error. In the mean time, I am looking into this further on my end.

**Comment by rickle-msft** [comment]
Also, have you assigned both Contributor and Storage Blob Data Contributor (SBDC) at the same time? Or just both independently?

**Comment by rickle-msft** [comment]
@marcioos Something else I can suggest is to look at how our tests use OAuth and see if that works in your context and try to adjust from there. You can find a sample test [here](https://github.com/Azure/azure-storage-java/blob/legacy-master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/OAuthTests.java) with some relevant helpers [here](https://github.com/Azure/azure-storage-java/blob/legacy-master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/TestHelper.java#L83). 

It's not immediately apparent to me why you are not able to authorize, so hopefully starting at this point getting a working baseline will help us figure out where the underlying issue is.

**Comment by marcioos** [comment]
Hey @rickle-msft, thanks for the assistance. Apparently it was just a matter of giving Azure some time to propagate the role assignment. It works with "Storage Blob Data Contributor" at resource group scope.

However, we'll probably end up not using RBAC. We stumbled on a limitation where SAS signatures cannot be generated without specifying the storage account key. Since our application needs to generate SAS signatures, we'll stick with key authentication for the time being.

We can probably close down this issue. I'll leave that for you, in case you want to follow up. Thanks again!

**Comment by rickle-msft** [comment]
Hey, @marcioos. That's good to hear! I am happy you were able to resolve the issue. 

I will add that there is a new service API called getUserDelegation key that returns a token which can be used to generate a SAS based on RBAC permissions. It looks like our docs have not been updated yet, but you can find the signature for the method to get the key [here](https://github.com/Azure/azure-storage-java/blob/legacy-dev/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudBlobClient.java#L646) and the method to generate the SAS [here](https://github.com/Azure/azure-storage-java/blob/legacy-master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudBlob.java#L2175). We do encourage people to use RBAC whenever possible, so if you'd like to/be able to use these methods, that'd be great. Of course, if you have a working solution, there's no need to mix things up just for the sake of it.

**Comment by rickle-msft** [comment]
I'll close this issue as you suggested it, but feel free to reopen it or post again if you have further questions or want help with the userDelegationSAS
