### ISSUE TITLE
http connection adds Java/1.7.0 to the User-Agent

### ISSUE THREAD

**Issue by SergeVil** [Azure/azure-storage-java#47]
Hi All,

There are companies that restrict the http requests outside unless they are sent from web browsers. I belive that you are using java.net.URLConnection in your code that adds Java/1.7.0 to the User-Agent. Even if I set up User-Agent as Mozilla, it's still present there because Oracle adds Java/1.7.0 and it cannot work at such companies.

Please, let me know how to resolve this problem, for me its a showstopper of using the azure cloud with my Java application. As the suggestion - you might consider of integration some other http client like apache that does not make this problem. I belive that it what your competitors (Amazon, Google) do, I do not see above problem with their libraries. 

Best,
Serge

**Comment by emgerner-msft** [comment]
Hi Serge,

Could you clarify how you’re setting up User-Agent? Are you using a proxy? What version of the library are you on and what version of Java are you on?

In general, if you’d like to override any header to something or add a header, you can use the below code. You would need to do this for any storage requests.
```
        HashMap<String, String> headers = new HashMap<String, String>();
        headers.put("User-Agent", "x");
        
        OperationContext opContext = new OperationContext();
        opContext.setUserHeaders(headers);

        this.container.downloadAttributes(null, null, opContext);
```

Best,
Emily

**Comment by emgerner-msft** [comment]
Closing issue as this hasn't had any recent activity. Feel free to reopen with any follow up questions or open a new issue with any additional questions!
