### ISSUE TITLE
SDK is throwing exceptions while sanitizing request URL for logging

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-storage-java#471]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
11.0.0

### What problem was encountered?
In one of our scenarios, customers provide SAS tokens and we just use that to make requests to storage service. If provided SAS tokens are invalid, then we'd expect storage service to return 401 or 403 responses. 
Before sending the request to storage service, SDK parses the URL to remove secrets and logs it. If there are any issues parsing the token (e.g., if date is used instead of timestamp for `st` in the token), it throws an IllegalArgumentException wrapped in RuntimeException and it's not easy to handle all the cases it would throw for. Perhaps it is better to not parse all the parameters for logging and just use regex to redact `sig` field.

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. I will schedule some time to verify this issue and work on a fix for it. We are still taking a look at some of the other requests, but I wanted to let you know that we have this seen this issue and will work on it accordingly.

**Comment by rickle-msft** [comment]
I am going to close this issue as we have GAed v12 which hopefully does not have this issue. Our current plan is to only release security fixes for v11 as necessary and to encourage upgrading to v12 for all other bug fixes.
