### ISSUE TITLE
How does netty client resolves blob host name to IP ?

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-storage-java#473]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
v 10.5 and v 11

### What problem was encountered?
I'm using proxy to connect my host to azure. I wanted to know how does netty-client resolves blob host-name to ip in some cases. Is there a way to not resolve the URL hostname and let proxy resolve it ? 

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
Hi, @vmaheshw. Just so I understand correctly--you are seeing that netty is resolving the hostname to the ip address, and you instead want netty to leave the host untouched so your proxy can observe it in some capacity?
