### ISSUE TITLE
Commit blob`s blocks in BlobOutputStream

### ISSUE THREAD

**Issue by ikryvorotenko** [Azure/azure-storage-java#476]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
Storage SDK v8 for Java

### What problem was encountered?
Can't commit intermediate blob blocks while using BlobOutputStream and thus encounter the error `The uncommitted block count cannot exceed the maximum limit of 100,000 blocks `

### Have you found a mitigation/solution?
I'm thinking about retrieving uncommitted blocks from azure, but that would require extra http request. I'm wondering if there is any way to commit intermediate blocks manually while using OutputStream of if not, if there's any workaround for that?

**Comment by rickle-msft** [comment]
Hi, @ikryvorotenko thank you for posting your question. We don't support committing intermediate blocks, but I think there's another thing that we can try before deciding whether or not we need to support that. Can you check what the value of streamWriteSizeInBytes is on your CloudBlockBlob object? It should default to 4MB, but the max is 100MB. This value should be what's used to determine when to add another uncommitted block to the blob, so if you increase this value, you should decrease the number of blocks you need and get under the 100k limit. Please let me know if you need further assistance or have more questions.

**Comment by ikryvorotenko** [comment]
@rickle-msft thanks for the suggestion. I checked that and technically that could solve my problem but I faced the restriction `A blob can have up to 100,000 uncommitted blocks, but their total size cannot exceed 200,000 MB.` from https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs.

Also, there's another version of that here https://docs.microsoft.com/en-us/rest/api/storageservices/Put-Block-List?redirectedfrom=MSDN:
```
The maximum number of uncommitted blocks that may be associated with a blob is 100,000, and the maximum size of the uncommitted block list is about 9.5 TB for version 2016-05-31 and later, and 400 GB for older versions.
```

Would you please clarify what restriction is relevant at this moment?

**Comment by rickle-msft** [comment]
My apologies for the delay. The information on the Put Block List api page is correct, so you should be able to have about 9.5TB uncommitted data associated with a blob. Does that higher limit solve your problem?

**Comment by ikryvorotenko** [comment]
yes, that fixed the problem, thanks!

**Comment by rickle-msft** [comment]
Excellent! I am going to close this issue as I believe your concerns have been addressed, but please feel free to continue to post here or in a new issue if you need further assistance.
