### ISSUE TITLE
How to generate SAS token and access using azure storage file sdk

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-storage-java#478]

**Comment by rickle-msft** [comment]
Hi, @warrenzhu25. CloudFile.generateSharedAccessSignature should get you what you want. There are also similar methods on CloudFileShare

**Comment by warrenzhu25** [comment]
Do you a working sample I can follow? BTW, how should I upload file share using SAS token? Thanks a lot.

**Comment by rickle-msft** [comment]
We don't have a sample in the samples file, but [here](https://github.com/Azure/azure-storage-java/blob/legacy-master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/file/FileSasTests.java#L262) is a test method that demonstrates the use of a share sas. You should be able to find everything you need there.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe the concerns have been addressed. Please feel free to continue to engage here if you have further questions.
