### ISSUE TITLE
Unable to use MSI with blob storage V11

### ISSUE THREAD

**Issue by yevster** [Azure/azure-storage-java#481]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
11.0.1

### What problem was encountered?
The REST v2 package does not include the `MSICredentials` and the `AppServiceMSICredentials` classes that were available in v1. Because Blob Storage v11 uses Rest v2, it is not possible to use MSI (in my case, in Azure functions)

### Have you found a mitigation/solution?
Falling back to version 8 storage SDK, which uses REST V1 package.

**Comment by rickle-msft** [comment]
Hi, @yevster. We are actually recommending that people stay on v8 for right now unless they need to use the async features of v11. We are in preview of v12 right now, which offers a similar upgrade as v11 but with a lot more stability and an improved api surface. 

That said, can you elaborate on the feature you are looking for? v8 doesn't actually depend on the restv1 package, and I'm not familiar with the MSICredentials and AppServiceMSICredentials types. I'd like to ensure we have support for anything you need in v12

**Comment by yevster** [comment]
Hi, Rick.
My mistake: I reverted to using the `com.microsoft.azure:azure` package, which pulls in `azure-storage:6.1.0`.

I was trying to write to a blob from an Azure Function, using MSI credentials for authentication.

Here's how I ended up doing it using the Azure SDK:
```java
Azure azure = Azure.authenticate(new AppServiceMSICredentials(AzureEnvironment.AZURE))
     .withSubscription(storageAccountSubscriptionId);
StorageAccount storageAccountInfo = azure.storageAccounts().getByResourceGroup(storageResourceGroup, storageAccountName);
```

The point is, I could only do that because Azure SDK uses Rest V1 for credentials.

Theoretically, I should be able to do something like this with Blob Storage v11:
```java
AppServiceMSICredentials msiCreds = new AppServiceMSICredentials(AzureEnvironment.AZURE);
HttpPipeline pipeline = StorageURL.createPipeline(msiCreds, new PipelineOptions());
URL u = new URL(String.format(Locale.ROOT, "https://myaccount.blob.core.windows.net"));
ServiceURL serviceURL = new ServiceURL(u, pipeline);
ContainerURL containerURL = serviceURL.createContainerURL("myjavacontainerbasic");
```

But this is currently not possible, because `AppServiceMSICredentials` is only available in REST v1, not v2.

**Comment by rickle-msft** [comment]
I think you may be looking for the management sdk, which is [here](https://github.com/Azure/azure-sdk-for-java/tree/master/storage/resource-manager/v2019_04_01/src/main/java/com/microsoft/azure/management/storage/v2019_04_01) (note the presence of the StorageAccount type, which is not a type found in this SDK). I wouldn't be surprised if some part of the Azure SDK pulls in this sdk and thus why you are seeing the dependency for this project. The management SDKs also does use the restv1 runtime, unlike this one. 

In any case, I think you are best sticking with v8 for now as it meets your needs, and we are recommending people either stay on v8 or try out the preview for v12 as v11 has some stability issues.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been resolved, but please feel free to reopen it or otherwise continue to engage if you need further support.

**Comment by lpghartz** [comment]
Just a comment in case anyone else runs across this -- it seems like Microsoft's official stance on using MSI to interact with storage is to use the management API to issue SAS tokens, which are then used by the storage client. Its a bit convoluted, but Storage seems to not be updated to support the newer Azure RBAC, and that's how they're "working around" it.

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-storage-sas
