### ISSUE TITLE
How to enable Azure Key Rotation with sdk?

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-storage-java#485]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
V10

### What problem was encountered?
How to support Azure Key Rotation with storage sdk without restarting the job?

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
Hi, @vmaheshw. 

Thank you for your question. Can you please give me a bit more info on what Azure Key Rotation is?

**Comment by vmaheshw** [comment]
"Use access keys to authenticate your applications when making requests to this Azure storage account. Store your access keys securely - for example, using Azure Key Vault - and don't share them. We recommend regenerating your access keys regularly. You are provided two access keys so that you can maintain connections using one key while regenerating the other.

When you regenerate your access keys, you must update any Azure resources and applications that access this storage account to use the new keys. This action will not interrupt access to disks from your virtual machines. "

https://docs.microsoft.com/en-us/azure/key-vault/key-vault-key-rotation-log-monitoring

**Comment by rickle-msft** [comment]
I think you are perhaps looking for the [resource-manager sdk](https://github.com/Azure/azure-sdk-for-java/tree/master/storage/resource-manager) (notice the types related to KeyVault Keys). This is the data plane SDK, and primarily supports data transfer and management. If that has what you're looking for, I'll request that you close this issue. If it does not, I will be happy to continue discussing.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been resolved, but please feel free to reopen it or otherwise continue to engage if you need further support.
