### ISSUE TITLE
How to list blob like Microsoft Azure Storage Explorer(not include his subfolder)?

### ISSUE THREAD

**Issue by zctzl** [Azure/azure-storage-java#486]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
v8 or v11

### What problem was encountered?
How to list files and directories only under the current folder(not include his subfolder) by Java. Similar to what we see in Microsoft Azure Storage Explorer(like the picture). Thank you!
![image](https://user-images.githubusercontent.com/29303849/62669619-cae04480-b9c2-11e9-8b62-b7880abb9ebd.png)

### Have you found a mitigation/solution?
Now,I only know how to list all bolb(include his subfolder), but I don't want to get his blob of  subfolder.

**Comment by rickle-msft** [comment]
I'll only address this in v8 as we are not recommending people work with v11 at the moment. 

This should actually be the default behavior if you call CloudBlobContainer.listBlobs(). This method will return a list of BlobItems that contains the blobs and directories immediately under the container (same is true for CloudBlobDirectory.listBlobs()). Is this not the result that you are seeing?

**Comment by zctzl** [comment]
Thanks for your answer. You are right . It's the default behavior with v8 which  is different from v11.
Now， I have a new problem. When I want to get the size of a blob,  I call the method (blob. getProperties (). getLength ()).  Only when I download the blob can I get the correct result, otherwise it will return 0. 
Here's my code and demo with gif.（v8）
![1](https://user-images.githubusercontent.com/29303849/62843924-2460b000-bcf0-11e9-9c09-e850ee5fc3ea.gif)
the file in blob:
![image](https://user-images.githubusercontent.com/29303849/62843964-815c6600-bcf0-11e9-9474-e6e8cc57e035.png)
when I want to get the file size, do I have to download it?

**Comment by rickle-msft** [comment]
@zctzl You don't have to download the whole file, but you at least have to make a getProperties call to the service. You can do that by calling downloadAttributes. In general, the client objects are not initialized until you start to interact with the service. This client-side caching and knowing when things are inconsistent is one of the most common issues we see with v8, which is why later versions have gotten rid of it.
