### ISSUE TITLE
Repos for other versions.

### ISSUE THREAD

**Issue by smccauliff** [Azure/azure-storage-java#490]
Where I can find the repo for v10.5?  I don't see any branches in this repo.

**Comment by rickle-msft** [comment]
If you're looking for the code for v10.5 in particular, you can find it [here](https://github.com/Azure/azure-storage-java/tree/12d9633c87a7531f56223783ce944a2da7c8872d). In general, you can go to Code->Releases and click on the commit ID of the release you want to see. 

If you're looking for where this code actually lives now, you can find that [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/microsoft-azure-storage-blob). Just to be safe, I'll reiterate what you should've seen in the issue template--we are encouraging people to move away from v10/11 in favor of 8 or 12 preview. If you still need 10/11 for some reason, by all means, but just wanted to make that clear.

**Comment by rickle-msft** [comment]
I am going to close this issue now as I believe your question has been addressed, but please feel free to reopen or continue engaging if you need further support.
