### ISSUE TITLE
Target GA date for V12

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-storage-java#491]
### Which service(blob, file, queue, table) does this issue concern?
BLOB

### Which version of the SDK was used?
Please note that if your issue is with v11, we are recommending customers either move back to v11 or move to v12 (currently in preview) if at all possible. Hopefully this resolves your issue, but if there is some reason why moving away from v11 is not possible at this time, please do continue to ask your question and we will do our best to support you. The README for this SDK has been updated to point to more information on why we have made this decision. 
V10.5.0

### What problem was encountered?
When is the target date for V12 GA?

### Have you found a mitigation/solution?
No

**Comment by rickle-msft** [comment]
@vmaheshw If you are not already aware, we released a GA version of 12.0.0 late last week. If you are still interested, please give it a try and let us know how we can support you in the transition. We will be happy, however, to support you as best we can on whichever version makes most sense for you for now. 

I am going to close this issue as I believe the discussion has been resolved, but please feel free to reopen it or reach out further if you need more assistance.
