### ISSUE TITLE
CloudBlockBlob upload() throw "The specified blob does not exist."

### ISSUE THREAD

**Issue by LingtaoKong** [Azure/azure-storage-java#50]
Version: 3.0.0
JDK: 1.8

I want to call upload() method to upload an input stream to CloudBlockBlob and specify the AccessCondition, when the input stream is not support mark and reset,  the 404(The specified blob does not exist.) exception will throw. 
thx.

The logs and call stacks: 
--------------------------------------------------------------------------------------------------
INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Starting operation.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:121)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Starting operation with location 'PRIMARY' per location mode 'PRIMARY_ONLY'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:153)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Starting request to 'http://micloudtest03.blob.core.chinacloudapi.cn/m03r/oOpTVdJdmGvD' at 'Mon, 14 Sep 2015 13:37:17 GMT'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:153)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Waiting for response.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:121)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Response received. Status code = '404', Request ID = 'aaa96386-0001-001c-3df2-eeb2e9000000', Content-MD5 = 'null', ETag = 'null', Date = 'Mon, 14 Sep 2015 13:37:34 GMT'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:131)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Processing response headers.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:121)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Response headers were processed successfully.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:121)

WARN :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Operation did not return the expected result or returned an exception.} 
==> com.microsoft.azure.storage.core.Logger.warn(Logger.java:208)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Checking if the operation should be retried. Retry count = '0', HTTP status code = '404', Error Message = 'The specified blob does not exist.'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:131)

INFO :{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {The next location has been set to 'PRIMARY', per location mode 'PRIMARY_ONLY'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:153)

ERROR:{e4d14a99-b27f-44d4-b4e3-0d0d02ec30eb}: {Retry policy did not allow for a retry. Failing. Error Message = 'The specified blob does not exist.'.} 
==> com.microsoft.azure.storage.core.Logger.error(Logger.java:99)

com.microsoft.azure.storage.StorageException: The specified blob does not exist.
	at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175)
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudBlob.downloadAttributes(CloudBlob.java:1392)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.openOutputStream(CloudBlockBlob.java:677)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:779)

**Comment by LingtaoKong** [comment]
version: 2.2.0 can not reproduce this problem.

**Comment by emgerner-msft** [comment]
Looks like we also got an email from you folks with the same logs and some source code. To follow up here as well in case someone else sees this issue, this is a bug in 3.0 affecting only larger blobs or blob streams sent with access conditions. We'll be addressing the issue in an upcoming fix.

**Comment by emgerner-msft** [comment]
Fixed in the latest release, 3.1.0. Please give it a try when you have a chance!

**Comment by LingtaoKong** [comment]
Thanks for your reply, I will try 3.1.0.

**Comment by LingtaoKong** [comment]
I have confirmed, the issue is not reproduced in version 3.1.0. Thanks again.

**Comment by emgerner-msft** [comment]
Thanks!
