### ISSUE TITLE
Use account SAS to access CloudTable throws "Server failed to authenticate the request"

### ISSUE THREAD

**Issue by LingtaoKong** [Azure/azure-storage-java#60]
I want to use an account SAS with full permissions of all of the services and resources to access  CloudBlockBlob and CloudTable。 The accesses to CloudBlockBlob, both container and blob are success,   BUT, the access to CloudTable is failed with "Server failed to authenticate the request".
Any help would be greatly appreciated.

The below is my code snippets.
-------------------------------------------------------------------------------
        String sas = "ss=bfqt&sig=[hidden]&st=2015-11-12T02%3A38%3A37Z&se=2016-01-11T02%3A38%3A37Z&sv=2015-04-05&srt=sco&spr=https&sp=racwdlup&sr=sco"
        CloudBlobContainer container = cloudBlobClient.getContainerReference("xxxxx");
        OperationContext operationContext = new OperationContext();
        operationContext.setLoggingEnabled(true);

        container.createIfNotExists(null,operationContext);

        CloudTableClient cloudTableClient = new CloudTableClient(new URI(tableURI), new StorageCredentialsSharedAccessSignature(rwSAS));
        final CloudTable table = cloudTableClient.getTableReference("zzzzz");
        table.createIfNotExists(null, operationContext);

The related log is below: 
----------------------------------------------
INFO :{7608b6ad-b647-4722-a20a-3a81d9a8d9d7}: {Starting request to 'https://micloudtest00.blob.core.chinacloudapi.cn/xxxxx?restype=container&ss=bfqt&sig=TU4whSinRFzR2dcsvkpAoa2DdEzfqnTEC%2BUzpG5Ub2U%3D&api-version=2015-04-05&st=2015-11-12T02%3A38%3A37Z&se=2016-01-11T02%3A38%3A37Z&sv=2015-04-05&srt=sco&spr=https&sp=racwdlup&sr=sco' at 'null'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:153)

INFO :{7608b6ad-b647-4722-a20a-3a81d9a8d9d7}: {Waiting for response.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:121)

INFO :{7608b6ad-b647-4722-a20a-3a81d9a8d9d7}: {Response received. Status code = '200', Request ID = '3a419393-0001-001f-34f4-1cb1ee000000', Content-MD5 = 'null', ETag = '"0x8D2EB0BA0289C7C"', Date = 'Thu, 12 Nov 2015 02:48:06 GMT'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:131)

INFO :{7608b6ad-b647-4722-a20a-3a81d9a8d9d7}: {Starting request to 'https://micloudtest00.table.core.chinacloudapi.cn/Tables('zzzzz')?ss=bfqt&sig=TU4whSinRFzR2dcsvkpAoa2DdEzfqnTEC%2BUzpG5Ub2U%3D&api-version=2015-04-05&st=2015-11-12T02%3A38%3A37Z&se=2016-01-11T02%3A38%3A37Z&sv=2015-04-05&srt=sco&spr=https&sp=racwdlup&sr=sco' at 'null'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:153)

INFO :{7608b6ad-b647-4722-a20a-3a81d9a8d9d7}: {Waiting for response.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:121)

INFO :{7608b6ad-b647-4722-a20a-3a81d9a8d9d7}: {Response received. Status code = '403', Request ID = '5f920386-0002-0016-48f4-1cab60000000', Content-MD5 = 'null', ETag = 'null', Date = 'Thu, 12 Nov 2015 02:48:07 GMT'.} 
==> com.microsoft.azure.storage.core.Logger.info(Logger.java:131)

**Comment by LingtaoKong** [comment]
Sorry, more information append:
azure-storage : 4.0.0
Java : jdk1.8.0_40
OS: centos 6.3 final

**Comment by pemari-msft** [comment]
Hi @LingtaoKong,

Account SAS functionalities are being rolled out in two phases. The first phase enabled full Blob and File access including management of Blob containers and File shares. The second phase will complete the Account SAS capabilities with Queues and Table support upcoming. This is why your table code works in dogfood but not in production at this time. 

[You can find more information about the release here](https://azure.microsoft.com/en-us/blog/azurecon-2015-azure-storage-announcements).

Thanks,
Peter

**Comment by LingtaoKong** [comment]
Hi Peter,
Thanks a lot for your reply. 
We will change to use other APIs  and I'm looking forward to the phase II.
Thanks again.
/Lingtao
