### ISSUE TITLE
Missing SAS support

### ISSUE THREAD

**Issue by DonMartin76** [Azure/azure-storage-java#61]
Hello,

Very nice to see support for Java clients for the Azure Storage Services.

What I'd actually need is support for creating Shared Access Signatures, so I could do things like those described in the following posts:
https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-shared-access-signature-part-1/
https://azure.microsoft.com/en-us/documentation/articles/storage-dotnet-shared-access-signature-part-2/

Is that planned?

*Edit*: I am sorry if I'm just being thick - I just found code on SAS, but not where I expected it (I was looking for the `GetSharedAccessSignature` method on Container and Blob). If this is already possible using the SDK, is there any kind of matching documentation for it?

Best regards,
Martin

**Comment by emgerner-msft** [comment]
Java has the exact same support and even almost the exact same format as these examples. With very minor ports you should be able to follow identically. For example, the naming is nearly identical with a couple differences -- ex the method names are lower case in Java per the language standards. Is there a particular aspect you're having trouble with?

**Comment by DonMartin76** [comment]
It was me being a little blind after all. I was looking for the `GetSharedAccessSignature` directly on Container and Blob, but it seems this is done in the `SharedAccessSignatureHelper`'s `generateSharedAccessSignatureForBlobAndFile` instead. Thanks!

**Comment by emgerner-msft** [comment]
There's also generateSharedAccessSignature directly on Container and Blob which is probably what you're looking for. :)
