### ISSUE TITLE
Accessing Azure storage through HTTP proxy

### ISSUE THREAD

**Issue by strazh** [Azure/azure-storage-java#65]
Continuing the discussion from https://github.com/Azure/azure-storage-java/issues/48 - the current API allows specifying the proxy in OperationContext. This requires to provide OperationContext parameter to every request. Can you please add an option to create a "default" OperationContext per ServiceClient - so that context configuration will be provided once on client creation?
The current requirement to specify the context in every request is bug-prone - API consumer might forget to add this paramer when adding new functionality.

**Comment by emgerner-msft** [comment]
The standard way to set a proxy is via Java itself. This can be done via System.setProperty() or when the VM is instantiated. The OperationContext route is meant as a workaround for using multiple proxies within the same library. What is your use case that the JVM route won't work?

**Comment by strazh** [comment]
My application needs to communicate with multiple web services, both internal and external to an organization, when only external services need to be accessed via proxy. That's why using system properties is not an option.
Please note that setting proxy per "client" is common practice. Examples for that can be Apache HttpClient library and Microsoft Azure adal4j authentication SDK.

**Comment by emgerner-msft** [comment]
Would a static proxy setting on OperationContext work for you? If not, could you explain your scenario a bit further?

**Comment by strazh** [comment]
Yes, a static setting on OperationContext will do the work.

**Comment by emgerner-msft** [comment]
If you check the thread you originally linked to that was the original proposal. It was rejected as being too inflexible. We can consider having both though. Expect to see something in the next release!

**Comment by strazh** [comment]
Great, thank you!

**Comment by ashvolunteering** [comment]
I still cannot figure out how to set the proxyUser and proxyPassword. I can set the proxy host and port using OperationContext and a Proxy object. But since the proxy class does not have a way to specify the proxy user id and password, I am struggling to get this working and I keep getting timeouts.

I tried settting run arguments for the VM as well as using System.setProperty but nothing is working.

Hopefully, this is something simple.

Any suggestions? The code works fine from home where I do not need to go through my company’s proxy server.

**Comment by emgerner-msft** [comment]
I'm removing the above comment as you've submitted it on two threads, and I answered on the other one. If you continue to have issues, please open a new issue as while your issue is proxy related it is not related to these closed threads.

**Comment by strazh** [comment]
Hello,

Is there any expectation on resolution of this issue?

Thank you.

**Comment by emgerner-msft** [comment]
It's in version 4.2 per the [changelog](https://github.com/Azure/azure-storage-java/blob/master/ChangeLog.txt#L2) and you can view the exact changes in [this commit](https://github.com/Azure/azure-storage-java/commit/85ffeb46856f591a65e681a9065cc7a1a356f83c). Sorry I forgot to update this thread! Give it a try and tell us if this works for you.

**Comment by strazh** [comment]
The change works just fine. Thank you very much!
