### ISSUE TITLE
Feature requests for table storage API

### ISSUE THREAD

**Issue by uded** [Azure/azure-storage-java#67]
Just a couple of feature requests of things that I find easy to modify and possibly very beneficial to developers. All regarding table storage as this is something I do work with at this specific point.
- `partitionKey` and `rowKey` should be managed using annotations or something similar. Naming those fields arbitrary would clean up the API quite well. Currently I am forced to use a simple workaround with my own getters and setters. And even the example in the documentation is using a workaround with constructor. Fairly simple to fix in my opinion.
- Serialization of more complex field types to string of a sort should be considered and, possibly, controlled with annotation as well. I do not see a reason why a complex object cannot be serialized to JSON for storage as byte array. If used purposefully it would be a great simplification for number of use cases. Now I use yet another workaround, but I do not see the point of not including that in the library and use as a common mechanism.

**Comment by emgerner-msft** [comment]
Thanks for following up! Here's some initial thoughts on the feature requests below to clarify what we can do to help best. In any case, I'll add them to our backlog but if we have a good plan we're more likely to please and more likely be able to get it done. :)

* Using annotations to handle pk/rk is something we have considered. It's not hard, but it's also not incredibly simple for a few reasons. One of these is maintaining backward compatibility with the existing code. TableEntity has getters/setters for pk/rk and library users have extended that class, so we have to maintain that functionality. Similarly, the notion of pk/rk being separate properties (hence their own getters/setters) is pretty baked into the existing design within the library so there would be some necessary refactors as well. If you have a design in mind that's non (or minimally) breaking to the API surface we can bounce some ideas back and forth.

* I think here I'd need some more clarification about what you had in mind for annotation. The purpose in general of using the getters/setters is that the user can do any necessary serialization inside the method itself. Given that there is a requirement that this lib work well with other languages in general we try to avoid language-specific solutions. For example, if we serialized a Java class and then tried to deserialize in Node, that wouldn't work well. Similarly, it's difficult to know exactly what to serialize in a class and we want to avoid serializing things that folks *don't* want (ex private fields). Serialization of complex types seems like one of those things that may be best be done in an application specific way for those and other reasons, but again we can discuss more what you have in mind.
