### ISSUE TITLE
Add a guide about running tests

### ISSUE THREAD

**Issue by dadoonet** [Azure/azure-storage-java#70]
Well, I'm trying to run tests using `mvn test` and it fails:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Microsoft Azure Storage Client SDK 4.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ azure-storage ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/dpilato/Documents/Elasticsearch/dev/3rdparty/azure-storage-java/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ azure-storage ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ azure-storage ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ azure-storage ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.13:test (default-test) @ azure-storage ---
[INFO] Surefire report directory: /Users/dpilato/Documents/Elasticsearch/dev/3rdparty/azure-storage-java/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
parallel='classes', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running com.microsoft.azure.storage.GenericTests
Tests run: 11, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.234 sec <<< FAILURE!
testReadTimeoutIssue(com.microsoft.azure.storage.GenericTests)  Time elapsed: 0.006 sec  <<< ERROR!
com.microsoft.azure.storage.StorageException: A Client side exception occurred, please check the inner exception for details
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseIPv6Reference(URI.java:3469)
	at java.net.URI$Parser.parseServer(URI.java:3219)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at com.microsoft.azure.storage.TestHelper.readTestConfigsFromXml(TestHelper.java:376)
	at com.microsoft.azure.storage.TestHelper.getAccount(TestHelper.java:308)
	at com.microsoft.azure.storage.TestHelper.createCloudBlobClient(TestHelper.java:56)
	at com.microsoft.azure.storage.GenericTests.testReadTimeoutIssue(GenericTests.java:74)

...

testCloudFileShareDeleteIfExists(com.microsoft.azure.storage.file.CloudFileShareTests)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.microsoft.azure.storage.file.CloudFileShareTests.fileShareTestMethodTearDown(CloudFileShareTests.java:63)

...

  LoggerTests.testStringToSign:260 » Storage A Client side exception occurred, p...

Tests run: 969, Failures: 0, Errors: 915, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.541 s
[INFO] Finished at: 2016-01-14T14:30:11+01:00
[INFO] Final Memory: 9M/309M
[INFO] ------------------------------------------------------------------------
```

Would it be possible to have a guide on how tests should be run?
Or may be it exists somewhere but I can't find it?

Thanks!

**Comment by dadoonet** [comment]
Reading the [source code](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/TestHelper.java#L270-L270), it sounds like you have to provide a system property:

* `storageConnection`
* `storageTestConfiguration`

Or a config file `TestConfigurations.xml`.

Will test that.

**Comment by dadoonet** [comment]
Sounds like you have to run the [Storage Simulator](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/#start-and-initialize-the-storage-emulator) which is available on Windows only, right?

I was hoping that maven tests would start such an emulator from whatever platform and then run tests against it...

**Comment by emgerner-msft** [comment]
The emulator doesn't support files or append blobs, so tests like testCloudFileShareDeleteIfExists would not work with an emulator. This is why we generally use live storage via the TestConfigurations in the test resources or a system property with a path to a TestConfigurations file.

Note that we don't generally test with Maven (though it is setup to work) and instead run via junit directly or Eclipse. If using the junit command line we have a variety of runners setup to use.

**Comment by dadoonet** [comment]
Thanks for the informations. Do you think you could come with a documentation which explains from A to Z how we can contribute to your code (which means IMO run/add tests)? If not, I/you should close this issue.

> The emulator doesn't support files or append blobs

Ha! That's too bad. I was looking for that to be able to test easily (not on a real cloud service) my azure repository plugin for elasticsearch... 
Sounds like I'm going to close https://github.com/elastic/elasticsearch/issues/15987 :'(

**Comment by emgerner-msft** [comment]
The emulator works for block blobs, page blobs, tables and queues which covers a lot of scenarios. Just not enough to fun a full storage pass with append and file. Since file is normally used for loading disks and less so for REST we haven't seen incredible push for this to be a feature though this could always change. You can use the emulator for your testing just fine for most features.

We can definitely add docs for how to run tests. Is there something you had trouble getting started with besides what we've already discussed?

**Comment by dadoonet** [comment]
I just started to install a VM with windows and installed the Azure SDK (I hope I choose the right one though because it was not obvious to me when I clicked on Microsoft Azure SDK on [this page](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/) which leads me to https://azure.microsoft.com/fr-fr/downloads/ which contains a lot of downloads but not really a "Microsoft Azure SDK" link...) :) 

I'll see if I can succeed in launching the emulator and connect to it using your test code and then my own code. I'll update the thread if needed.

I just opened this issue as it took me some time to figure out what I have to do and how.

As an example, I only found that I have to define a system property and its name by reading the [source code](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/TestHelper.java#L277-L293)! 

I just supposed that this system property should may be contain: 

```
Account name: devstoreaccount1
Account key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
```

I'm still unsure though. I mean that it's probably obvious for a .Net developer but for a Java developer that's another story :P 

Anyhow thanks for your help and feedback so far.

**Comment by emgerner-msft** [comment]
https://github.com/Azure/azure-storage-java/wiki/Developing-for-the-Azure-Storage-Java-Library

Keep in mind the emulator is great for doing dev work, but you definitely should test any code you intend to use in production on a real storage account. The emulator is a good approximation of the service, but as you may have noticed in the emulator getting started you linked to there still are some differences.

If using the emulator, going the connection string route for the tests and specifying 'UseDevelopmentStorage=true;' would be my route of choice, though as always there's a lot of ways to do this.

**Comment by emgerner-msft** [comment]
Closing this as resolved as I posted a guide per the original question and haven't heard from you since.

**Comment by dadoonet** [comment]
Sorry. I did not follow up on this. You know... Busy days... :) Whatever. I'll definitely test it and comment here if needed.
