### ISSUE TITLE
Support for client side timeout

### ISSUE THREAD

**Issue by dadoonet** [Azure/azure-storage-java#72]
Follow up of #71.

We have a server side timeout but that would be super handy to have a client side timeout.

So we could say that when we start to send a request to Azure storage, if we don't get any answer after x seconds we throw an IOException.

WDYT? Is that feasible?

**Comment by pemari-msft** [comment]
Please take a look at BlobRequestOptions.MaximumExecutionTime. That's a client side timeout across all retries.

**Comment by dadoonet** [comment]
Oh? Fantastic @pemari-msft! Thanks. Closing then.
