### ISSUE TITLE
blockBlob.getProperties().getLength() returns 0 even though its Having some data

### ISSUE THREAD

**Issue by abhinayabhi** [Azure/azure-storage-java#75]
I created new BlockBlob and uploaded Text into it after uploading I am calling out the BlockBlob.getProperties().getLength() and it returns value as zero instead of showing the actual blobsize in bytes. I am getting issue in 4.0.0.0 version not tested in older versions.

**Comment by pemari-msft** [comment]
You need to call `.downloadAttributes()` to fetch the properties/metadata from the service before checking the value in the Properties object.

**Comment by abhinayabhi** [comment]
Thanks that worked :)

**Comment by rajvael** [comment]
Thanks its working
