### ISSUE TITLE
UTF-8 characters in metadata return strange error

### ISSUE THREAD

**Issue by librucha** [Azure/azure-storage-java#76]
When added metadata 
`file_name=ŠKODA_OCTAVIA_III_CPOJ-zápis-z-prohlídky_20160129_143601.pdf`
response is
`com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`
and response status is 403
![image](https://cloud.githubusercontent.com/assets/1335068/12677652/c61b478e-c69a-11e5-91cc-6db2aa5f3008.png)

**Comment by emgerner-msft** [comment]
The supported characters in the metadata must be ASCII characters. To work around this you can either escape the string (percent encode), base64 encode, etc.
