### ISSUE TITLE
Is there a plan to upgrade the dependency for jersey?

### ISSUE THREAD

**Issue by kennethinsnow** [Azure/azure-storage-java#79]
Its on com.sun.jersey jersey 1.13 now, but the current jersey is at 2.22 and package name is changed to org.glassfish.jersey. Jersey 2 uses Jax-rs for a lot more things now to replace its own implementations so it is not a trivia change. 

I wonder if you have a plan to do so because My project has upgraded to jersey 2 but it also depends on this package and its causing serious dependency problems for me (dropwizard related, because it mystically pull dependencies from both jersey 1 and 2 if both are available).

Thanks,

**Comment by emgerner-msft** [comment]
I'm a little confused. Our current release doesn't depend on Jersey, at least directly. You can see in the [POM](https://github.com/Azure/azure-storage-java/blob/master/pom.xml) that Jackson-core, slf4j-api, and commons-lang3 are our only dependencies. I took a quick look at their sub dependencies and I didn't see Jersey either, though maybe I missed it? Why are you thinking we're using Jersey?

**Comment by kennethinsnow** [comment]
Sorry, it is azure media that's depending on jersey

**Comment by kennethinsnow** [comment]
Since i already got your attention I would ask another question which i am not sure if it qualifies as an issue. 
My test is reporting
java.lang.SecurityException: class "com.microsoft.azure.storage.blob.ListBlobItem"'s signer information does not match signer information of other classes in the same package
It seems like some classes in azure are pulling from different azure packages. I have these in my dependency tree:
[INFO] +- com.yammer.azure:azure-queue-core:jar:1.7:compile
[INFO] +- com.microsoft.azure:azure-storage:jar:4.0.0:compile
[INFO] +- com.microsoft.azure:azure-media:jar:0.9.2:compile
[INFO] |  +- com.microsoft.azure:azure-core:jar:0.9.2:compile
Did you ever see this before and what could be the causes for the signer mismatch?

Thanks

**Comment by emgerner-msft** [comment]
I'm happy to help, but could you please open another issue including the full stack trace? 

The title for this one is Jersey and it looks like we figured out that issue, so I'd like to close this topic. :)

**Comment by kennethinsnow** [comment]
Thanks. Please close this issue. I'll open anther one.
