### ISSUE TITLE
Issue in CloudFile.getProperties().getLength()- Unable to find the length/size of the file

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-storage-java#82]
I have uploaded gzip files in MS web portal to one of my file storage account. In java web app before start the file download, I need to check the length of the file but CloudFile.getProperties().getLength() always return 0(zero). Please let me know this is an known issue and any other alternative methods available to identify the file size.

**Comment by pemari-msft** [comment]
Please see issue 75: https://github.com/Azure/azure-storage-java/issues/75 

Let me know if that doesn't solve your issue.

**Comment by rajvael** [comment]
Thanks its working
