### ISSUE TITLE
Synchronous or Asynchronous?

### ISSUE THREAD

**Issue by pedromss** [Azure/azure-storage-java#95]
Among other utilities I used the `CloudBlob.download(...)` method which is blocking.

Is the whole API blocking (i.e not asynchronous)?

If the answer is "no" please state why (maybe with a code example).

**Comment by esummers-msft** [comment]
All of the blob download APIs in our Java library are synchronous. The method will not terminate until the download is complete. In general Java 6 (the version we use) does not support asynchronous methods.
Hope this helps!

**Comment by pedromss** [comment]
What about the methods that upload or append content to a blob? Or retrieve a message from a queue? Are these operations synchronous aswell?

**Comment by esummers-msft** [comment]
Yes, because Java 6 does not support asynchronous methods.

**Comment by pedromss** [comment]
Thank you, that helps.
