### ISSUE TITLE
Is this the right way to do SharedAccessSignature ?

### ISSUE THREAD

**Issue by raintears** [Azure/azure-storage-java#96]
Hi,

I tried the following and It uploads the file i want to my container even though the permissions is set to read only. 

```
SharedAccessBlobPolicy policy = new SharedAccessBlobPolicy();
policy.setPermissions(EnumSet.of(SharedAccessBlobPermissions.READ));
BlobContainerPermissions permissions  = new BlobContainerPermissions();
permissions.setPublicAccess(BlobContainerPublicAccessType.OFF);
permissions.getSharedAccessPolicies().put("default", policy);
container.uploadPermissions(permissions);
CloudBlockBlob blob = container.getBlockBlobReference("test");
blob.upload ...
```

anyone knows what's wrong with the SAS code? Did i miss out anything?

**Comment by emgerner-msft** [comment]
The container object was created with Shared Key credentials or it wouldn't be able to set a policy in the first place. Then you used that container with Shared Key credentials to upload a blob. This of course worked. If you created a SAS token with the name of your policy and creates a container object with that as the credentials this would work exactly as expected.

**Comment by raintears** [comment]
I create a container object using my user account and key and then set a stored access policy and upload it. I tried uploading a file using the same container object but it's not making use of the policy. 

I then tried to generate a shared access signature using the container object. I constructed a URI reference to the blob file I'm going to upload to azure and create a new blockblob object with the signature. however, it is returning me 403, server failed to authenticate the request now and that the value of authorization header is not formed correctly.

**Comment by emgerner-msft** [comment]
The first paragraph makes sense. Like I said, the library uses the Shared Key Credentials since that's what you created the container object with. Setting policies just means you can create SAS with them -- they don't do anything special within themselves.

If you're having trouble constructing a SAS token after setting the policies on the container, please post the code you're using the construct the SAS and the code you're using to set the SAS token as your credentials.

**Comment by pemari-msft** [comment]
Closing for non-response, please reopen if you need. Thanks!
