### ISSUE TITLE
API to download incremental updates to Blob 

### ISSUE THREAD

**Issue by sujitrect** [Azure/azure-storage-java#99]
Hi, my scenario is to monitor a continuously updating blob (it's set as output of an azure stream analytics job) and to get the latest increments at some fixed time intervals (say, 5 or 10s). My blob is not expected to become very big (will remain <10Mb). I tried the various CloudBlockBlob's download* and downloadRange* methods but I am not getting the response fast enough to be useful. Even for a blob below 10Kb in size, the methods are taking 15-20 secs to return. 
I was hoping if there is a faster mechanism of getting the updates to the blob downloaded to my client.

**Comment by emgerner-msft** [comment]
I wouldn't expect to see that sort of performance and running these methods locally on my box I'm not seeing that sort of performance. Could you do some benchmarking of your application to determine exactly where the bottleneck is? Is it possible you're having network issues?

**Comment by sujitrect** [comment]
I guess you are right. I was on a slower network yesterday.
So, i am closing this.
